// context/LanguageContext.tsx
import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Lang = 'ar' | 'en';

const AR = {
  // Auth
  appName: 'راحتي',
  appTagline: 'رفيقك في إدارة طاقتك',
  appTagline2: 'رفيقك اليومي للصحة والعافية',
  signIn: 'تسجيل الدخول',
  signUp: 'إنشاء حساب',
  email: 'البريد الإلكتروني',
  password: 'كلمة المرور',
  confirmPassword: 'تأكيد كلمة المرور',
  noAccount: 'ليس لديك حساب؟',
  haveAccount: 'لديك حساب بالفعل؟',
  welcome: 'أهلاً بعودتك 👋',
  orWith: 'أو تابع بواسطة',
  google: 'جوجل',
  facebook: 'فيسبوك',
  continueBtn: 'متابعة',
  startDay: 'ابدأ يومك',
  required: 'هذا الحقل مطلوب',
  invalidEmail: 'البريد الإلكتروني غير صحيح',
  shortPassword: 'كلمة المرور 6 أحرف على الأقل',
  passwordMismatch: 'كلمتا المرور غير متطابقتين',
  invalidAge: 'يرجى إدخال عمر صحيح',
  // Sign-up
  personalInfo: 'المعلومات الشخصية',
  enterPersonalInfo: 'أدخل معلوماتك الشخصية',
  accountData: 'بيانات الحساب',
  createAccount: 'أنشئ بيانات حسابك',
  firstName: 'الاسم الأول',
  lastName: 'الاسم الثاني',
  age: 'العمر',
  gender: 'الجنس',
  male: 'ذكر',
  female: 'أنثى',
  step1of2: 'الخطوة 1 من 2',
  step2of2: 'الخطوة 2 من 2',
  // Startup
  welcomeTo: 'مرحباً بك في راحتي',
  hello: 'مرحباً،',
  meditation: 'تأمل',
  nutrition: 'تغذية',
  exercises: 'تمارين',
  // Tabs
  home: 'الرئيسية',
  tasks: 'مهامي',
  exercisesTab: 'تمارين',
  more: 'المزيد',
  // Tasks screen
  myTasks: 'مهامي',
  completedOf: 'مكتملة',
  from: 'من',
  todayProgress: 'تقدمك اليوم',
  all: 'الكل',
  work: 'عمل',
  study: 'دراسة',
  atHome: 'منزل',
  addTask: 'إضافة مهمة',
  taskTitle: 'عنوان المهمة',
  taskTime: 'الوقت',
  taskEnergy: 'استهلاك الطاقة (%)',
  taskCategory: 'التصنيف',
  cancel: 'إلغاء',
  add: 'إضافة',
  taskCoding: 'العمل على الكمبيوتر',
  taskReading: 'القراءة والمطالعة',
  taskCooking: 'الطبخ والإعداد',
  taskCleaning: 'التنظيف والترتيب',
  // Tasks - new
  taskType: 'نوع المهمة',
  taskTypeCore: 'أساسي 🔁',
  taskTypeExtra: 'إضافي ⚡ (اليوم بس)',
  taskName: 'اسم المهمة *',
  taskIcon: 'الإيقونة (إيموجي)',
  taskCategory2: 'التصنيف',
  taskEnergyConsumed: 'الطاقة المستهلكة (%)',
  taskNamePlaceholder: 'مثال: قراءة كتاب...',
  taskEnergyPlaceholder: 'مثال: 20',
  addNewTask: 'إضافة مهمة جديدة',
  addTaskBtn: '✚ إضافة المهمة',
  taskOptions: 'خيارات المهمة',
  moveToExtra: '⚡ حوّل لإضافي',
  moveToCore: '⭐ حوّل لأساسي',
  deleteTask: '🗑️ حذف',
  taskMoved: 'تم التحويل ✅',
  taskMovedToCore: 'الأساسي',
  taskMovedToExtra: 'الإضافي',
  taskDeleted: 'تم حذف المهمة 🗑️',
  coreTasks: 'الأساسي',
  extraTasks: 'الإضافي',
  coreTasksHint: 'مهام يومية ثابتة — اضغط مطولاً للخيارات',
  extraTasksHint: 'مهام إضافية ليوم واحد فقط — اضغط مطولاً للخيارات',
  noCoreTasksYet: 'مفيش مهام أساسية بعد',
  noExtraTasksToday: 'مفيش مهام إضافية لليوم دة',
  noTasksInCategory: 'لا توجد مهام في هذا التصنيف',
  saving: 'جاري الحفظ...',
  // Exercises
  todayExercises: 'تمارين اليوم',
  chooseExercise: 'اختر تمريناً لتبدأ',
  startExercise: 'ابدأ التمرين',
  timeRemaining: 'الوقت المتبقي',
  exerciseDone: 'أحسنت! اكتمل التمرين 🎉',
  pause: 'إيقاف مؤقت',
  resume: 'استمرار',
  stop: 'إيقاف',
  // Exercises - new
  exerciseOptions: 'خيارات التمرين',
  moveExerciseToExtra: '⚡ حوّل لإضافي',
  moveExerciseToCore: '⭐ حوّل لأساسي',
  addNewExercise: 'إضافة تمرين جديد',
  exerciseType: 'نوع التمرين',
  exerciseEmoji: 'الإيموجي',
  exerciseNameLabel: 'اسم التمرين *',
  exerciseDurationLabel: 'المدة بالدقائق *',
  exerciseDescLabel: 'وصف (اختياري)',
  exerciseNamePlaceholder: 'مثال: مشي على السلم',
  exerciseDurationPlaceholder: 'مثال: 5',
  exerciseDescPlaceholder: 'وصف قصير للتمرين',
  saveExercise: '✅ حفظ التمرين',
  longPressForOptions: 'اضغط مطولاً للخيارات',
  coreExercises: 'الأساسي',
  extraExercises: 'الإضافي',
  coreExercisesHint: 'تمارين يومية ثابتة — موجودة دايماً',
  extraExercisesHint: 'تمارين إضافية ليوم واحد فقط',
  noCoreExercises: 'مفيش تمارين أساسية بعد',
  noExtraExercises: 'مفيش تمارين إضافية لليوم دة',
  addExercise: 'أضف تمرين',
  stopExercise: 'إيقاف التمرين',
  startExerciseWithDuration: 'ابدأ التمرين',
  readSteps: 'اقرأ الخطوات',
  exerciseMoved: 'تم التحويل ✅',
  exerciseDeleted: 'تم حذف التمرين 🗑️',
  exerciseAdded: 'تمت إضافة تمرين ✅',
  dailyExercises: 'تمارين اليوم',
  quickExercise: 'تمرين سريع',
  customExercise: '✨ تمرين مخصص',
  // Home screen
  myPlan: 'خطتي اليوم',
  notifications: 'الإشعارات',
  energySufficient: 'طاقتك كافية لمهام اليوم',
  energyInsufficient: 'طاقتك قد لا تكفي لكل المهام',
  organizedByEnergy: 'تم تنظيم يومك بناءً\nعلى طاقتك البالغة',
  noTasksToday: 'لا توجد مهام في هذا اليوم',
  addTasksFromTasksPage: 'أضف مهام من صفحة المهام',
  allDone: '🎉 أنهيت كل مهام اليوم! عظيم!',
  done: 'منجز',
  notDoneYet: 'لم يتم بعد',
  notTimeYet: 'لسه وقته ماجاش',
  exercise: 'تمرين',
  doneLabel: '✅ تم الإنجاز',
  lockedLabel: '⏳ لسه وقته ماجاش',
  energyWarning: 'طاقتك قد لا تكفي لهذه المهمة',
  coreTasksCount: 'أساسي',
  extraTasksCount: 'إضافي',
  exercisesCount: 'تمرين',
  // Calendar
  calMonths: ['يناير','فبراير','مارس','أبريل','مايو','يونيو','يوليو','أغسطس','سبتمبر','أكتوبر','نوفمبر','ديسمبر'],
  calDays: ['أح','اث','ث','أر','خ','ج','س'],
  // Energy screen
  myEnergyToday: 'طاقتي اليوم',
  whatIsYourEnergy: 'ما هي طاقتك اليوم؟',
  chooseEnergyLevel: 'اختر نسبة طاقتك اليوم',
  saveEnergy: 'حفظ الطاقة',
  energyExhausted: 'منهك',
  energyMedium: 'متوسطة',
  energyGood: 'جيدة',
  energyExcellent: 'ممتازة',
  // Notifications screen
  notificationsTitle: 'الإشعارات',
  unread: 'غير مقروءة',
  read: 'تم قراءتها',
  allRead: 'كل الإشعارات اتقرأت ✅',
  noNotifications: 'مفيش إشعارات',
  noNotificationsSubtitle: 'هتظهر هنا لما يحصل أي تحديث في الأبليكيشن',
  tapForDetails: 'اضغط للتفاصيل',
  okBtn: 'حسناً 👍',
  notifTypeTask: 'مهمة',
  notifTypeBreak: 'استراحة',
  notifTypeEnergy: 'طاقة',
  notifTypeAdd: 'إضافة',
  notifTypeDelete: 'حذف',
  notifTypeUpdate: 'تحديث',
  // Notification service
  taskNearTitle: 'موعد مهمة قريب ⏰',
  exerciseNearTitle: 'موعد تمرين قريب ⏰',
  taskNear10: 'هيبدأ بعد 10 دقايق',
  taskNear5: 'هيبدأ بعد 5 دقايق، استعد!',
  taskNowTitle: 'وقت المهمة دلوقتي! 🚀',
  exerciseNowTitle: 'وقت التمرين دلوقتي! 🚀',
  startNow: 'ابدأ',
  nowLabel: 'دلوقتي',
  missedTask: 'مهمة فاتتك! 😔',
  missedExercise: 'تمرين فاتتك! 😔',
  missedTaskBody: 'فاتت ومعلمتهاش كمنجزة',
  taskCompleted: 'أحسنت! مهمة منجزة 🎉',
  taskCompletedBody: 'بنجاح! استمر في التقدم 💪',
  exerciseCompleted: 'تمرين ناجح! 💪',
  exerciseCompletedBody: 'بنجاح! جسمك بيشكرك 🌟',
  energyRaised: 'ارتفع',
  energyLowered: 'انخفض',
  energyLevelChanged: 'مستوى الطاقة',
  energyNow: 'طاقتك دلوقتي',
  taskAddedNotif: 'تمت إضافة مهمة جديدة ✅',
  taskAddedBody: 'اتضافت للخطة',
  tasksAddedBody: 'مهمة للخطة',
  taskDeletedNotif: 'تم حذف مهمة 🗑️',
  tasksDeletedBody: 'مهمة من الخطة',
  dailyReminder: '🌿 تذكير يومي',
  dailyReminderBody: 'حان وقت مراجعة مهامك وتمارينك اليوم 💪',
  // More / Profile
  profile: 'الملف الشخصي',
  accountInfo: 'معلومات الحساب',
  settings: 'الإعدادات',
  editProfile: 'تعديل الملف الشخصي',
  language: 'اللغة',
  privacy: 'الخصوصية والأمان',
  help: 'المساعدة والدعم',
  logout: 'تسجيل الخروج',
  logoutConfirm: 'هل أنت متأكد أنك تريد الخروج؟',
  confirm: 'تأكيد',
  version: 'الإصدار 1.0.0',
  years: 'سنة',
  save: 'حفظ التغييرات',
  editProfileTitle: 'تعديل الملف الشخصي',
  error: 'خطأ',
  nameRequired: 'الاسم الأول والأخير مطلوبان.',
  saveFailed: 'فشل الحفظ. حاول مجدداً.',
  savingProfile: 'جارٍ الحفظ…',
  selectLanguage: 'اختر لغتك المفضلة',
  pushNotifications: 'الإشعارات الفورية',
  emailNotifications: 'إشعارات البريد الإلكتروني',
  reminders: 'التذكيرات',
  appUpdates: 'تحديثات التطبيق',
  faq1q: 'كيف أحدّث ملفي الشخصي؟',
  faq1a: 'اذهب إلى المزيد ← تعديل الملف الشخصي وحدّث معلوماتك.',
  faq2q: 'كيف أغيّر اللغة؟',
  faq2a: 'اذهب إلى المزيد ← اللغة واختر لغتك المفضلة.',
  faq3q: 'كيف أتواصل مع الدعم؟',
  faq3a: 'راسلنا على support@rahati.app وسنرد خلال 24 ساعة.',
  photoPermissionRequired: 'يجب منح إذن الوصول إلى الصور.',
  longPressHint: '👆 اضغط مطوّل لخيارات الصورة',
  photoTitle: 'صورتك الشخصية',
  photoSubtitle: 'خليها تعبّر عنك! 🌟',
  changePhoto: 'غيّر الصورة',
  addPhoto: 'أضف صورة',
  deletePhoto: 'احذف الصورة',
  quickLinks: 'روابط سريعة',
  myPlanLink: 'خطتي',
  exercisesLink: 'تمارين',
  tasksLink: 'مهامي',
  alertsLink: 'إشعارات',
  highEnergy: 'طاقة عالية',
  mediumEnergy: 'طاقة متوسطة',
  lowEnergy: 'طاقة منخفضة',
  generalSettings: 'إعدادات عامة',
  appNotifications: '🔔 إشعارات التطبيق',
  appNotificationsDesc: 'تفعيل أو إيقاف جميع إشعارات التطبيق',
  dailyReminderLabel: '⏰ تذكير يومي بالمهام',
  dailyReminderDesc: 'إشعار يومي يذكرك بمراجعة مهامك وتمارينك',
  reminderTime: '🕐 وقت التذكير',
  reminderTimeHint: 'هتوصلك إشعار كل يوم الساعة',
  serverNotifNote: 'إشعارات البريد الإلكتروني وتحديثات التطبيق تحتاج اتصال بالسيرفر وغير متاحة حالياً.',
  saveSettings: '💾 حفظ الإعدادات',
  profileUpdated: 'تم تحديث الملف الشخصي ✅',
  profileUpdatedBody: 'تم حفظ بياناتك بنجاح',
  notifPermError: 'فشل الحفظ، تأكد من صلاحيات الإشعارات',
  // Reset app
  resetApp: 'Reset App',
  resetDone: '✅ تم المسح',
  resetMsg: 'أُعيد تعيين التطبيق — أغلقه وافتحه من جديد',

  // ── Doctor-specific ────────────────────────────────────
  // Role choose
  docRoleTitle: 'من أنت؟',
  docRoleSubtitle: 'اختر دورك للمتابعة',
  docRoleDoctor: 'دكتور',
  docRoleDoctorSub: 'متابعة المرضى وإدارة التمارين',
  docRolePatient: 'مريض',
  docRolePatientSub: 'متابعة تمارينك وصحتك اليومية',
  docContinue: 'متابعة',
  // Doctor home
  docGreeting: 'أهلاً، د.',
  docManagePatients: 'إدارة المرضى والطلبات',
  docActivePatients: 'مرضى نشطون',
  docPendingRequests: 'طلبات انتظار',
  docTotal: 'إجمالي',
  docSearchPatient: 'ابحث عن مريض...',
  docAcceptedOnly: 'تظهر هنا محادثات المرضى المقبولين فقط',
  docNewRequest: 'طلب جديد',
  docChatOpen: 'شات مفتوح',
  docRequestedOn: 'طلب في',
  docPendingNeedsAccept: 'طلبات تحتاج قبول',
  docActivePatientsList: 'المرضى النشطون',
  docNoPatients: 'لا يوجد مرضى بعد',
  docNoPatientsSubtitle: 'ستظهر طلبات المرضى هنا عند وصولها',
  docLoading: 'جاري التحميل...',
  docAllTab: 'الكل',
  docActiveTab: 'نشطون',
  docPendingTab: 'انتظار',
  docAcceptRequest: 'قبول الطلب',
  docAcceptBody: 'هل تريد قبول طلب',
  docAcceptBody2: 'وفتح شات معه؟',
  docAcceptNow: 'لأ دلوقتي',
  docConfirmAccept: 'قبول',
  // Doctor chat list
  docChats: 'المحادثات',
  docUnreadMessages: 'رسالة غير مقروءة',
  docSearchChats: 'ابحث في المحادثات...',
  docNoChats: 'لا توجد محادثات بعد',
  docNoChatsSubtitle: 'المحادثات ستظهر هنا فقط للمرضى الذين قبلت طلباتهم',
  // Doctor patient chat
  docActiveNow: 'نشط الآن',
  docQuickReplies: ['كيف حالك اليوم؟', 'هل تناولت الدواء؟', 'ما هي الأعراض؟', 'لا داعي للقلق', 'يرجى المراجعة غداً'],
  docWriteMessage: 'اكتب رسالة...',
  docToday: 'اليوم',
  // Doctor exercises
  docPatientExercises: 'تمارين المريض',
  docAssignExercise: 'تعيين تمرين',
  docExerciseName: 'اسم التمرين *',
  docExerciseDuration: 'المدة (دقائق) *',
  docExerciseDesc: 'وصف (اختياري)',
  docExerciseEmoji: 'إيموجي',
  docSaveExercise: '✅ حفظ التمرين',
  docNoExercises: 'لم يتم تعيين تمارين بعد',
  docRemoveExercise: 'حذف التمرين',
  docExerciseAdded: 'تم إضافة تمرين ✅',
  docExerciseRemoved: 'تم حذف التمرين 🗑️',
  docViewExercises: 'عرض التمارين',
  docOpenChat: 'فتح الشات',
  // Doctor more / profile
  docMyAccount: 'حسابي',
  docDoctor: 'دكتور',
  docSpecialty: 'التخصص',
  docLicense: 'رقم الترخيص',
  docSpecialtyNotSet: 'التخصص غير محدد',
  docTotalPatients: 'إجمالي المرضى',
  docActivePatientsStat: 'مرضى نشطون',
  docSessions: 'الجلسات',
  docQuickLinksPatients: 'المرضى',
  docQuickLinksExercises: 'التمارين',
  docQuickLinksSessions: 'الجلسات',
  docQuickLinksAlerts: 'إشعارات',
  docPhotoSubtitle: 'صورة احترافية تعكس ثقتك! 🩺',
  // Doctor notifications
  docNotificationsTitle: 'إشعارات الدكتور',
  docNotifNewRequest: 'طلب مريض جديد 🆕',
  docNotifRequestAccepted: 'تم قبول مريض ✅',
  docNotifNewMessage: 'رسالة جديدة 💬',
  docNotifExerciseAssigned: 'تمرين مُعيَّن 🏋️',
  docNotifUnread: 'غير مقروءة',
  docNotifRead: 'مقروءة',
  docClearAll: 'مسح الكل',
  docNoNotifs: 'لا توجد إشعارات',
  docNoNotifsSubtitle: 'ستظهر هنا إشعارات المرضى والشات',
};

const EN: typeof AR = {
  appName: 'Rahati',
  appTagline: 'Your energy management companion',
  appTagline2: 'Your daily health & wellness buddy',
  signIn: 'Sign In',
  signUp: 'Create Account',
  email: 'Email Address',
  password: 'Password',
  confirmPassword: 'Confirm Password',
  noAccount: "Don't have an account?",
  haveAccount: 'Already have an account?',
  welcome: 'Welcome back 👋',
  orWith: 'Or continue with',
  google: 'Google',
  facebook: 'Facebook',
  continueBtn: 'Continue',
  startDay: 'Start Your Day',
  required: 'This field is required',
  invalidEmail: 'Invalid email address',
  shortPassword: 'Password must be at least 6 characters',
  passwordMismatch: 'Passwords do not match',
  invalidAge: 'Please enter a valid age',
  personalInfo: 'Personal Information',
  enterPersonalInfo: 'Enter your personal details',
  accountData: 'Account Data',
  createAccount: 'Create your account credentials',
  firstName: 'First Name',
  lastName: 'Last Name',
  age: 'Age',
  gender: 'Gender',
  male: 'Male',
  female: 'Female',
  step1of2: 'Step 1 of 2',
  step2of2: 'Step 2 of 2',
  welcomeTo: 'Welcome to Rahati',
  hello: 'Hello,',
  meditation: 'Meditation',
  nutrition: 'Nutrition',
  exercises: 'Exercises',
  home: 'Home',
  tasks: 'Tasks',
  exercisesTab: 'Exercises',
  more: 'More',
  myTasks: 'My Tasks',
  completedOf: 'completed',
  from: 'of',
  todayProgress: "Today's Progress",
  all: 'All',
  work: 'Work',
  study: 'Study',
  atHome: 'Home',
  addTask: 'Add Task',
  taskTitle: 'Task Title',
  taskTime: 'Time',
  taskEnergy: 'Energy Cost (%)',
  taskCategory: 'Category',
  cancel: 'Cancel',
  add: 'Add',
  taskCoding: 'Computer Work',
  taskReading: 'Reading & Study',
  taskCooking: 'Cooking',
  taskCleaning: 'Cleaning & Tidying',
  taskType: 'Task Type',
  taskTypeCore: 'Core 🔁',
  taskTypeExtra: 'Extra ⚡ (Today only)',
  taskName: 'Task name *',
  taskIcon: 'Icon (emoji)',
  taskCategory2: 'Category',
  taskEnergyConsumed: 'Energy consumed (%)',
  taskNamePlaceholder: 'e.g. Read a book...',
  taskEnergyPlaceholder: 'e.g. 20',
  addNewTask: 'Add New Task',
  addTaskBtn: '✚ Add Task',
  taskOptions: 'Task Options',
  moveToExtra: '⚡ Move to Extra',
  moveToCore: '⭐ Move to Core',
  deleteTask: '🗑️ Delete',
  taskMoved: 'Task Moved ✅',
  taskMovedToCore: 'Core',
  taskMovedToExtra: 'Extra',
  taskDeleted: 'Task Deleted 🗑️',
  coreTasks: 'Core',
  extraTasks: 'Extra',
  coreTasksHint: 'Daily fixed tasks — long press for options',
  extraTasksHint: 'Extra tasks for today only — long press for options',
  noCoreTasksYet: 'No core tasks yet',
  noExtraTasksToday: 'No extra tasks for today',
  noTasksInCategory: 'No tasks in this category',
  saving: 'Saving...',
  todayExercises: "Today's Exercises",
  chooseExercise: 'Choose an exercise to start',
  startExercise: 'Start Exercise',
  timeRemaining: 'Time Remaining',
  exerciseDone: 'Well done! Exercise complete 🎉',
  pause: 'Pause',
  resume: 'Resume',
  stop: 'Stop',
  exerciseOptions: 'Exercise Options',
  moveExerciseToExtra: '⚡ Move to Extra',
  moveExerciseToCore: '⭐ Move to Core',
  addNewExercise: 'Add New Exercise',
  exerciseType: 'Exercise Type',
  exerciseEmoji: 'Emoji',
  exerciseNameLabel: 'Exercise name *',
  exerciseDurationLabel: 'Duration (minutes) *',
  exerciseDescLabel: 'Description (optional)',
  exerciseNamePlaceholder: 'e.g. Stair walking',
  exerciseDurationPlaceholder: 'e.g. 5',
  exerciseDescPlaceholder: 'Short description',
  saveExercise: '✅ Save Exercise',
  longPressForOptions: 'Long press for options',
  coreExercises: 'Core',
  extraExercises: 'Extra',
  coreExercisesHint: 'Daily fixed exercises — always available',
  extraExercisesHint: 'Extra exercises for today only',
  noCoreExercises: 'No core exercises yet',
  noExtraExercises: 'No extra exercises for today',
  addExercise: 'Add Exercise',
  stopExercise: 'Stop Exercise',
  startExerciseWithDuration: 'Start',
  readSteps: 'Read steps aloud',
  exerciseMoved: 'Exercise Moved ✅',
  exerciseDeleted: 'Exercise Deleted 🗑️',
  exerciseAdded: 'Exercise Added ✅',
  dailyExercises: "Today's Exercises",
  quickExercise: 'Quick Exercise',
  customExercise: '✨ Custom exercise',
  myPlan: 'My Plan Today',
  notifications: 'Notifications',
  energySufficient: "Your energy is sufficient for today's tasks",
  energyInsufficient: 'Your energy may not be enough for all tasks',
  organizedByEnergy: 'Your day is organized based\non your energy level of',
  noTasksToday: 'No tasks for this day',
  addTasksFromTasksPage: 'Add tasks from the Tasks page',
  allDone: '🎉 You completed all tasks today! Amazing!',
  done: 'Done',
  notDoneYet: 'Not done yet',
  notTimeYet: 'Not time yet',
  exercise: 'Exercise',
  doneLabel: '✅ Completed',
  lockedLabel: '⏳ Not time yet',
  energyWarning: 'Your energy may not be enough for this task',
  coreTasksCount: 'Core',
  extraTasksCount: 'Extra',
  exercisesCount: 'Exercises',
  calMonths: ['January','February','March','April','May','June','July','August','September','October','November','December'],
  calDays: ['Su','Mo','Tu','We','Th','Fr','Sa'],
  myEnergyToday: 'My Energy Today',
  whatIsYourEnergy: 'What is your energy today?',
  chooseEnergyLevel: 'Choose your energy level for today',
  saveEnergy: 'Save Energy',
  energyExhausted: 'Exhausted',
  energyMedium: 'Medium',
  energyGood: 'Good',
  energyExcellent: 'Excellent',
  notificationsTitle: 'Notifications',
  unread: 'Unread',
  read: 'Read',
  allRead: 'All notifications have been read ✅',
  noNotifications: 'No notifications',
  noNotificationsSubtitle: 'They will appear here when there are updates in the app',
  tapForDetails: 'Tap for details',
  okBtn: 'OK 👍',
  notifTypeTask: 'Task',
  notifTypeBreak: 'Break',
  notifTypeEnergy: 'Energy',
  notifTypeAdd: 'Added',
  notifTypeDelete: 'Deleted',
  notifTypeUpdate: 'Updated',
  taskNearTitle: 'Task coming up ⏰',
  exerciseNearTitle: 'Exercise coming up ⏰',
  taskNear10: 'starts in 10 minutes',
  taskNear5: 'starts in 5 minutes, get ready!',
  taskNowTitle: "It's task time! 🚀",
  exerciseNowTitle: "It's exercise time! 🚀",
  startNow: 'Start',
  nowLabel: 'now',
  missedTask: 'Missed task! 😔',
  missedExercise: 'Missed exercise! 😔',
  missedTaskBody: 'has passed and was not marked as done',
  taskCompleted: 'Well done! Task completed 🎉',
  taskCompletedBody: 'successfully! Keep up the progress 💪',
  exerciseCompleted: 'Exercise complete! 💪',
  exerciseCompletedBody: 'successfully! Your body thanks you 🌟',
  energyRaised: 'increased',
  energyLowered: 'decreased',
  energyLevelChanged: 'Energy level',
  energyNow: 'Your energy is now',
  taskAddedNotif: 'New task added ✅',
  taskAddedBody: 'was added to the plan',
  tasksAddedBody: 'tasks added to the plan',
  taskDeletedNotif: 'Task deleted 🗑️',
  tasksDeletedBody: 'tasks removed from the plan',
  dailyReminder: '🌿 Daily Reminder',
  dailyReminderBody: "Time to check today's tasks and exercises 💪",
  profile: 'Profile',
  accountInfo: 'Account Information',
  settings: 'Settings',
  editProfile: 'Edit Profile',
  language: 'Language',
  privacy: 'Privacy & Security',
  help: 'Help & Support',
  logout: 'Log Out',
  logoutConfirm: 'Are you sure you want to log out?',
  confirm: 'Confirm',
  version: 'Version 1.0.0',
  years: 'years',
  save: 'Save Changes',
  editProfileTitle: 'Edit Profile',
  error: 'Error',
  nameRequired: 'First and last name are required.',
  saveFailed: 'Failed to save. Try again.',
  savingProfile: 'Saving…',
  selectLanguage: 'Choose your preferred language',
  pushNotifications: 'Push Notifications',
  emailNotifications: 'Email Notifications',
  reminders: 'Reminders',
  appUpdates: 'App Updates',
  faq1q: 'How do I update my profile?',
  faq1a: 'Go to More → Edit Profile and update your information.',
  faq2q: 'How do I change the language?',
  faq2a: 'Go to More → Language and select your preferred language.',
  faq3q: 'How do I contact support?',
  faq3a: "Email us at support@rahati.app and we'll reply within 24 hours.",
  photoPermissionRequired: 'Permission to access photos is required.',
  longPressHint: '👆 Long press for photo options',
  photoTitle: 'Profile Photo',
  photoSubtitle: 'Make it yours! 🌟',
  changePhoto: 'Change Photo',
  addPhoto: 'Add Photo',
  deletePhoto: 'Delete Photo',
  quickLinks: 'Quick Links',
  myPlanLink: 'My Plan',
  exercisesLink: 'Exercises',
  tasksLink: 'Tasks',
  alertsLink: 'Alerts',
  highEnergy: 'High Energy',
  mediumEnergy: 'Medium Energy',
  lowEnergy: 'Low Energy',
  generalSettings: 'General Settings',
  appNotifications: '🔔 App Notifications',
  appNotificationsDesc: 'Enable or disable all app notifications',
  dailyReminderLabel: '⏰ Daily Task Reminder',
  dailyReminderDesc: 'Daily notification to review tasks and exercises',
  reminderTime: '🕐 Reminder Time',
  reminderTimeHint: "You'll get a notification every day at",
  serverNotifNote: 'Email notifications and app updates require a server connection and are not available yet.',
  saveSettings: '💾 Save Settings',
  profileUpdated: 'Profile Updated ✅',
  profileUpdatedBody: 'Your profile has been updated successfully',
  notifPermError: 'Save failed, check notification permissions',
  resetApp: 'Reset App',
  resetDone: '✅ Done',
  resetMsg: 'App reset — close and reopen it',

  // ── Doctor-specific ────────────────────────────────────
  docRoleTitle: 'Who are you?',
  docRoleSubtitle: 'Choose your role to continue',
  docRoleDoctor: 'Doctor',
  docRoleDoctorSub: 'Follow up with patients & manage exercises',
  docRolePatient: 'Patient',
  docRolePatientSub: 'Track your exercises & daily health',
  docContinue: 'Continue',
  docGreeting: 'Hello, Dr.',
  docManagePatients: 'Manage patients & requests',
  docActivePatients: 'Active Patients',
  docPendingRequests: 'Pending Requests',
  docTotal: 'Total',
  docSearchPatient: 'Search patient...',
  docAcceptedOnly: "Only accepted patients' chats appear here",
  docNewRequest: 'New Request',
  docChatOpen: 'Chat open',
  docRequestedOn: 'Requested on',
  docPendingNeedsAccept: 'Requests needing approval',
  docActivePatientsList: 'Active Patients',
  docNoPatients: 'No patients yet',
  docNoPatientsSubtitle: 'Patient requests will appear here when received',
  docLoading: 'Loading...',
  docAllTab: 'All',
  docActiveTab: 'Active',
  docPendingTab: 'Pending',
  docAcceptRequest: 'Accept Request',
  docAcceptBody: 'Do you want to accept the request from',
  docAcceptBody2: 'and open a chat?',
  docAcceptNow: 'Not now',
  docConfirmAccept: 'Accept',
  docChats: 'Chats',
  docUnreadMessages: 'unread messages',
  docSearchChats: 'Search chats...',
  docNoChats: 'No chats yet',
  docNoChatsSubtitle: 'Chats will appear here only for accepted patients',
  docActiveNow: 'Active now',
  docQuickReplies: ['How are you today?', 'Did you take your medicine?', 'What are the symptoms?', 'No need to worry', 'Please come in tomorrow'],
  docWriteMessage: 'Write a message...',
  docToday: 'Today',
  docPatientExercises: 'Patient Exercises',
  docAssignExercise: 'Assign Exercise',
  docExerciseName: 'Exercise name *',
  docExerciseDuration: 'Duration (minutes) *',
  docExerciseDesc: 'Description (optional)',
  docExerciseEmoji: 'Emoji',
  docSaveExercise: '✅ Save Exercise',
  docNoExercises: 'No exercises assigned yet',
  docRemoveExercise: 'Remove Exercise',
  docExerciseAdded: 'Exercise Added ✅',
  docExerciseRemoved: 'Exercise Removed 🗑️',
  docViewExercises: 'View Exercises',
  docOpenChat: 'Open Chat',
  docMyAccount: 'My Account',
  docDoctor: 'Doctor',
  docSpecialty: 'Specialty',
  docLicense: 'License Number',
  docSpecialtyNotSet: 'Specialty not set',
  docTotalPatients: 'Total Patients',
  docActivePatientsStat: 'Active Patients',
  docSessions: 'Sessions',
  docQuickLinksPatients: 'Patients',
  docQuickLinksExercises: 'Exercises',
  docQuickLinksSessions: 'Sessions',
  docQuickLinksAlerts: 'Alerts',
  docPhotoSubtitle: 'Professional photo that reflects your confidence! 🩺',
  docNotificationsTitle: 'Doctor Notifications',
  docNotifNewRequest: 'New Patient Request 🆕',
  docNotifRequestAccepted: 'Patient Accepted ✅',
  docNotifNewMessage: 'New Message 💬',
  docNotifExerciseAssigned: 'Exercise Assigned 🏋️',
  docNotifUnread: 'Unread',
  docNotifRead: 'Read',
  docClearAll: 'Clear All',
  docNoNotifs: 'No notifications',
  docNoNotifsSubtitle: 'Patient and chat notifications will appear here',
};

// ── التعديل الجوهري: استخدام typeof AR بدل interface يدوي ──
interface LangContextType {
  lang: Lang;
  t: typeof AR;   // ← هذا يضمن إن TypeScript يعرف كل الـ keys تلقائياً
  setLang: (l: Lang) => void;
  isRTL: boolean;
}

const LangContext = createContext<LangContextType | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>('ar');
  const t = lang === 'ar' ? AR : EN;
  const isRTL = lang === 'ar';
  return (
    <LangContext.Provider value={{ lang, t, setLang, isRTL }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  const ctx = useContext(LangContext);
  if (!ctx) throw new Error('useLang must be inside LanguageProvider');
  return ctx;
}