// context/LanguageContext.tsx
import React, { createContext, useContext, useState, useEffect, useCallback, ReactNode } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { doc, setDoc } from 'firebase/firestore';
import { auth, db } from '../utils/firebaseConfig';

const LANG_KEY = 'app_language';

export type Lang = 'ar' | 'en';

const AR = {
  // ── Auth ──────────────────────────────────────────────────────────────────
  appName: 'حكاية حركة',
  appTagline: 'رفيقك في إدارة طاقتك',
  appTagline2: 'رفيقك اليومي للصحة والعافية',
  signIn: 'تسجيل الدخول',
  signUp: 'إنشاء حساب',
  email: 'البريد الإلكتروني',
  password: 'كلمة المرور',
  confirmPassword: 'تأكيد كلمة المرور',
  noAccount: 'ليس لديك حساب؟',
  haveAccount: 'لديك حساب بالفعل؟',
  welcome: 'أهلاً بعودتك 👋',
  orWith: 'أو تابع بواسطة',
  google: 'جوجل',
  facebook: 'فيسبوك',
  continueBtn: 'متابعة',
  startDay: 'ابدأ يومك',
  required: 'هذا الحقل مطلوب',
  invalidEmail: 'البريد الإلكتروني غير صحيح',
  shortPassword: 'كلمة المرور 6 أحرف على الأقل',
  passwordMismatch: 'كلمتا المرور غير متطابقتين',
  invalidAge: 'يرجى إدخال عمر صحيح',
  personalInfo: 'المعلومات الشخصية',
  enterPersonalInfo: 'أدخل معلوماتك الشخصية',
  accountData: 'بيانات الحساب',
  createAccount: 'أنشئ بيانات حسابك',
  firstName: 'الاسم الأول',
  lastName: 'الاسم الثاني',
  age: 'العمر',
  gender: 'الجنس',
  male: 'ذكر',
  female: 'أنثى',
  step1of2: 'الخطوة 1 من 2',
  step2of2: 'الخطوة 2 من 2',
  welcomeTo: 'مرحباً بك في راحتي',
  hello: 'مرحباً،',

  // ── Navigation / Tabs ─────────────────────────────────────────────────────
  home: 'الرئيسية',
  tasks: 'مهامي',
  exercisesTab: 'تمارين',
  more: 'المزيد',
  meditation: 'تأمل',
  nutrition: 'تغذية',
  exercises: 'تمارين',

  // ── Tasks Screen ──────────────────────────────────────────────────────────
  myTasks: 'مهامي',
  completedOf: 'مكتملة',
  from: 'من',
  todayProgress: 'تقدمك اليوم',
  all: 'الكل',
  work: 'عمل',
  study: 'دراسة',
  atHome: 'منزل',
  addTask: 'إضافة مهمة',
  taskTitle: 'عنوان المهمة',
  taskTime: 'الوقت',
  taskEnergy: 'استهلاك الطاقة (%)',
  taskCategory: 'التصنيف',
  cancel: 'إلغاء',
  add: 'إضافة',
  taskCoding: 'العمل على الكمبيوتر',
  taskReading: 'القراءة والمطالعة',
  taskCooking: 'الطبخ والإعداد',
  taskCleaning: 'التنظيف والترتيب',
  taskType: 'نوع المهمة',
  taskTypeCore: 'أساسي 🔁',
  taskTypeExtra: 'إضافي ⚡ (اليوم بس)',
  taskName: 'اسم المهمة *',
  taskIcon: 'الإيقونة (إيموجي)',
  taskCategory2: 'التصنيف',
  taskEnergyConsumed: 'الطاقة المستهلكة (%)',
  taskNamePlaceholder: 'مثال: قراءة كتاب...',
  taskEnergyPlaceholder: 'مثال: 20',
  addNewTask: 'إضافة مهمة جديدة',
  addTaskBtn: '✚ إضافة المهمة',
  taskOptions: 'خيارات المهمة',
  moveToExtra: '⚡ حوّل لإضافي',
  moveToCore: '⭐ حوّل لأساسي',
  deleteTask: '🗑️ حذف',
  taskMoved: 'تم التحويل ✅',
  taskMovedToCore: 'الأساسي',
  taskMovedToExtra: 'الإضافي',
  taskDeleted: 'تم حذف المهمة 🗑️',
  coreTasks: 'الأساسي',
  extraTasks: 'الإضافي',
  coreTasksHint: 'مهام يومية ثابتة — اضغط مطولاً للخيارات',
  extraTasksHint: 'مهام إضافية ليوم واحد فقط — اضغط مطولاً للخيارات',
  noCoreTasksYet: 'مفيش مهام أساسية بعد',
  noExtraTasksToday: 'مفيش مهام إضافية لليوم دة',
  noTasksInCategory: 'لا توجد مهام في هذا التصنيف',
  saving: 'جاري الحفظ...',
  taskTimeFrom: 'من',
  taskTimeTo: 'إلى',
  taskTimeFromPlaceholder: '09:00 ص',
  taskTimeToPlaceholder: '10:00 ص',
  taskNameRequired: 'يرجى إدخال اسم المهمة',
  taskNameRequiredEn: 'Please enter task name',
  savingDots: 'جاري الحفظ...',

  // ── Exercises Screen ──────────────────────────────────────────────────────
  todayExercises: 'تمارين اليوم',
  chooseExercise: 'اختر تمريناً لتبدأ',
  startExercise: 'ابدأ التمرين',
  timeRemaining: 'الوقت المتبقي',
  exerciseDone: 'أحسنت! اكتمل التمرين 🎉',
  pause: 'إيقاف مؤقت',
  resume: 'استمرار',
  stop: 'إيقاف',
  exerciseOptions: 'خيارات التمرين',
  moveExerciseToExtra: '⚡ حوّل لإضافي',
  moveExerciseToCore: '⭐ حوّل لأساسي',
  addNewExercise: 'إضافة تمرين جديد',
  exerciseType: 'نوع التمرين',
  exerciseEmoji: 'الإيموجي',
  exerciseNameLabel: 'اسم التمرين *',
  exerciseDurationLabel: 'المدة بالدقائق *',
  exerciseDescLabel: 'وصف (اختياري)',
  exerciseNamePlaceholder: 'مثال: مشي على السلم',
  exerciseDurationPlaceholder: 'مثال: 5',
  exerciseDescPlaceholder: 'وصف قصير للتمرين',
  saveExercise: '✅ حفظ التمرين',
  longPressForOptions: 'اضغط مطولاً للخيارات',
  coreExercises: 'الأساسي',
  extraExercises: 'الإضافي',
  coreExercisesHint: 'تمارين يومية ثابتة — موجودة دايماً',
  extraExercisesHint: 'تمارين إضافية ليوم واحد فقط',
  noCoreExercises: 'مفيش تمارين أساسية بعد',
  noExtraExercises: 'مفيش تمارين إضافية لليوم دة',
  addExercise: 'أضف تمرين',
  stopExercise: 'إنهاء التمرين',
  startExerciseWithDuration: 'ابدأ التمرين',
  readSteps: 'اقرأ الخطوات',
  exerciseMoved: 'تم التحويل ✅',
  exerciseDeleted: 'تم حذف التمرين 🗑️',
  exerciseAdded: 'تمت إضافة تمرين ✅',
  dailyExercises: 'تمارين اليوم',
  quickExercise: 'تمرين سريع',
  customExercise: '✨ تمرين مخصص',
  exerciseMinute: 'دقيقة',
  exerciseNoSection: 'مفيش تمارين في قسم',
  exerciseNoSectionYet: 'بعد',
  exerciseAddBtn: 'أضف تمرين',
  exerciseSectionDesc_therapy: 'تمارين علاج طبيعي وتأهيل',
  exerciseSectionDesc_yoga: 'وضعيات اليوغا والاسترخاء',
  exerciseSectionDesc_aerobic: 'تمارين القلب والأوعية الدموية',
  exerciseSectionDesc_endurance: 'تمارين القوة والتحمّل',
  exerciseSectionDesc_strength: 'تمارين تقوية العضلات والمفاصل',
  exerciseSectionDesc_coordination: 'تمارين التناسق الحركي والتوازن',
  doctorExercise: 'دكتور',
  exerciseDoneDr: 'تم إنجاز التمرين ✓',
  exerciseTapWhenDone: 'اضغط عند الإنهاء',
  startSession: 'ابدأ التمرين',
  startDot: 'ابدأ · ',
  stopReadSteps: 'إيقاف',

  // ── Exercise Session Screen ────────────────────────────────────────────────
  sessionRunning: 'جلسة التمرين جارية',
  sessionPaused: 'متوقف مؤقتاً ⏸',
  sendAttachment: 'إرسال مرفق',
  camera: 'كاميرا',
  gallery: 'صور',
  file: 'ملف',
  muted: 'الصوت مكتوم 🔇',
  endExercise: 'إنهاء التمرين',
  wellDoneComplete: 'أحسنت! انتهى التمرين 🎉',

  // ── Home / Plan Screen ────────────────────────────────────────────────────
  myPlan: 'خطتي اليوم',
  notifications: 'الإشعارات',
  energyZero: 'أضف مهام لترى مستوى طاقتك',
  energySufficient: 'طاقتك كافية لمهام اليوم',
  energyInsufficient: 'طاقتك قد لا تكفي لكل المهام',
  organizedByEnergy: 'تم تنظيم يومك بناءً\nعلى طاقتك البالغة',
  noTasksToday: 'لا توجد مهام في هذا اليوم',
  addTasksFromTasksPage: 'أضف مهام من صفحة المهام',
  allDone: '🎉 أنهيت كل مهام اليوم! عظيم!',
  done: 'منجز',
  notDoneYet: 'لم يتم بعد',
  notTimeYet: 'لسه وقته ماجاش',
  exercise: 'تمرين',
  doneLabel: '✅ تم الإنجاز',
  lockedLabel: '⏳ لسه وقته ماجاش',
  energyWarning: 'طاقتك قد لا تكفي لهذه المهمة',
  coreTasksCount: 'أساسي',
  extraTasksCount: 'إضافي',
  exercisesCount: 'تمرين',
  calMonths: ['يناير','فبراير','مارس','أبريل','مايو','يونيو','يوليو','أغسطس','سبتمبر','أكتوبر','نوفمبر','ديسمبر'],
  calDays: ['أح','اث','ث','أر','خ','ج','س'],
  basicTask: '⭐ أساسي',
  extraTaskBadge: '⚡ إضافي',
  quickExerciseBadge: 'تمرين سريع',
  noTasksDay: 'لا توجد مهام في هذا اليوم',
  addTasksBtn: 'أضف مهام من صفحة المهام',
  energyOkLabel: 'طاقتك كافية لمهام اليوم',
  energyLowLabel: 'طاقتك قد لا تكفي لكل المهام',
  planToday: 'خطتي اليوم',
  yesterday: 'أمس',
  completedCount: 'مكتملة',
  pastDayViewMode: 'عرض سجل الأمس — لا يمكن التعديل',
  futureDayPlanMode: 'تخطيط مسبق — المهام لا تُحسب حتى يحين يومها',
  planForDay: 'خطط مهام لهذا اليوم',
  noTasksPastDay: 'لا توجد مهام مسجلة لهذا اليوم',
  calFullDays: ['الأحد','الاثنين','الثلاثاء','الأربعاء','الخميس','الجمعة','السبت'],

  // ── Energy Screen ─────────────────────────────────────────────────────────
  myEnergyToday: 'طاقتي اليوم',
  whatIsYourEnergy: 'ما هي طاقتك اليوم؟',
  chooseEnergyLevel: 'اختر نسبة طاقتك اليوم',
  saveEnergy: 'حفظ الطاقة',
  energyExhausted: 'منهك',
  energyMedium: 'متوسطة',
  energyGood: 'جيدة',
  energyExcellent: 'ممتازة',

  // ── Notifications ─────────────────────────────────────────────────────────
  notificationsTitle: 'الإشعارات',
  unread: 'غير مقروءة',
  read: 'تم قراءتها',
  allRead: 'كل الإشعارات اتقرأت ✅',
  noNotifications: 'مفيش إشعارات',
  noNotificationsSubtitle: 'هتظهر هنا لما يحصل أي تحديث في الأبليكيشن',
  tapForDetails: 'اضغط للتفاصيل',
  okBtn: 'حسناً 👍',
  notifTypeTask: 'مهمة',
  notifTypeBreak: 'استراحة',
  notifTypeEnergy: 'طاقة',
  notifTypeAdd: 'إضافة',
  notifTypeDelete: 'حذف',
  notifTypeUpdate: 'تحديث',
  taskNearTitle: 'موعد مهمة قريب ⏰',
  exerciseNearTitle: 'موعد تمرين قريب ⏰',
  taskNear10: 'هيبدأ بعد 10 دقايق',
  taskNear5: 'هيبدأ بعد 5 دقايق، استعد!',
  taskNowTitle: 'وقت المهمة دلوقتي! 🚀',
  exerciseNowTitle: 'وقت التمرين دلوقتي! 🚀',
  startNow: 'ابدأ',
  nowLabel: 'دلوقتي',
  missedTask: 'مهمة فاتتك! 😔',
  missedExercise: 'تمرين فاتتك! 😔',
  missedTaskBody: 'فاتت ومعلمتهاش كمنجزة',
  taskCompleted: 'أحسنت! مهمة منجزة 🎉',
  taskCompletedBody: 'بنجاح! استمر في التقدم 💪',
  exerciseCompleted: 'تمرين ناجح! 💪',
  exerciseCompletedBody: 'بنجاح! جسمك بيشكرك 🌟',
  energyRaised: 'ارتفع',
  energyLowered: 'انخفض',
  energyLevelChanged: 'مستوى الطاقة',
  energyNow: 'طاقتك دلوقتي',
  taskAddedNotif: 'تمت إضافة مهمة جديدة ✅',
  taskAddedBody: 'اتضافت للخطة',
  tasksAddedBody: 'مهمة للخطة',
  taskDeletedNotif: 'تم حذف مهمة 🗑️',
  tasksDeletedBody: 'مهمة من الخطة',
  dailyReminder: '🌿 تذكير يومي',
  dailyReminderBody: 'حان وقت مراجعة مهامك وتمارينك اليوم 💪',
  notifTaskNear10Body: 'هيبدأ بعد 10 دقايق',
  notifTaskNear5Body: 'هيبدأ بعد 5 دقايق، استعد!',
  notifTaskNowBody: 'ابدأ',
  notifTaskLabel: 'مهمة',
  notifExerciseLabel: 'تمرين',
  notifMissedBody: 'فاتت ومعلمتهاش كمنجزة',
  notifTaskCompletedTitle: 'أحسنت! مهمة منجزة 🎉',
  notifTaskCompletedBody: 'بنجاح! استمر في التقدم 💪',
  notifExerciseCompletedTitle: 'تمرين ناجح! 💪',
  notifExerciseCompletedBody: 'بنجاح! جسمك بيشكرك 🌟',
  notifEnergyRaised: 'ارتفع',
  notifEnergyLowered: 'انخفض',
  notifEnergyTitle: 'مستوى الطاقة',
  notifEnergyBody: 'طاقتك دلوقتي',
  appNotifications: '🔔 إشعارات التطبيق',
  appNotificationsDesc: 'تفعيل أو إيقاف جميع إشعارات التطبيق',
  dailyReminderLabel: '⏰ تذكير يومي بالمهام',
  dailyReminderDesc: 'إشعار يومي يذكرك بمراجعة مهامك وتمارينك',
  reminderTime: '🕐 وقت التذكير',
  reminderTimeHint: 'هتوصلك إشعار كل يوم الساعة',
  serverNotifNote: 'إشعارات البريد الإلكتروني وتحديثات التطبيق تحتاج اتصال بالسيرفر وغير متاحة حالياً.',
  saveSettings: '💾 حفظ الإعدادات',

  // ── More / Profile Screen (Patient) ──────────────────────────────────────
  profile: 'الملف الشخصي',
  accountInfo: 'معلومات الحساب',
  settings: 'الإعدادات',
  editProfile: 'تعديل الملف الشخصي',
  language: 'اللغة',
  privacy: 'الخصوصية والأمان',
  help: 'المساعدة والدعم',
  logout: 'تسجيل الخروج',
  logoutConfirm: 'هل أنت متأكد أنك تريد الخروج؟',
  confirm: 'تأكيد',
  version: 'الإصدار 1.0.0',
  years: 'سنة',
  save: 'حفظ التغييرات',
  editProfileTitle: 'تعديل الملف الشخصي',
  error: 'خطأ',
  invalidCredential: 'البريد الإلكتروني أو كلمة المرور غير صحيحة',
  authError: 'حدث خطأ، حاول مجدداً',
  userDataNotFound: 'لم يتم العثور على بيانات المستخدم، حاول مجدداً',
  nameRequired: 'الاسم الأول والأخير مطلوبان.',
  saveFailed: 'فشل الحفظ. حاول مجدداً.',
  savingProfile: 'جارٍ الحفظ…',
  selectLanguage: 'اختر لغتك المفضلة',
  pushNotifications: 'الإشعارات الفورية',
  emailNotifications: 'إشعارات البريد الإلكتروني',
  reminders: 'التذكيرات',
  appUpdates: 'تحديثات التطبيق',
  faq1q: 'كيف أحدّث ملفي الشخصي؟',
  faq1a: 'اذهب إلى المزيد ← تعديل الملف الشخصي وحدّث معلوماتك.',
  faq2q: 'كيف أغيّر اللغة؟',
  faq2a: 'اذهب إلى المزيد ← اللغة واختر لغتك المفضلة.',
  faq3q: 'كيف أتواصل مع الدعم؟',
  faq3a: 'راسلنا على support@rahati.app وسنرد خلال 24 ساعة.',
  photoPermissionRequired: 'يجب منح إذن الوصول إلى الصور.',
  longPressHint: '👆 اضغط مطوّل لخيارات الصورة',
  photoTitle: 'صورتك الشخصية',
  photoSubtitle: 'خليها تعبّر عنك! 🌟',
  changePhoto: 'غيّر الصورة',
  addPhoto: 'أضف صورة',
  deletePhoto: 'احذف الصورة',
  quickLinks: 'روابط سريعة',
  myPlanLink: 'خطتي',
  exercisesLink: 'تمارين',
  tasksLink: 'مهامي',
  alertsLink: 'إشعارات',
  highEnergy: 'طاقة عالية',
  mediumEnergy: 'طاقة متوسطة',
  lowEnergy: 'طاقة منخفضة',
  generalSettings: 'إعدادات عامة',
  profileUpdated: 'تم تحديث الملف الشخصي ✅',
  profileUpdatedBody: 'تم حفظ بياناتك بنجاح',
  notifPermError: 'فشل الحفظ، تأكد من صلاحيات الإشعارات',
  resetApp: 'إعادة ضبط التطبيق',
  resetDone: '✅ تم المسح',
  resetMsg: 'أُعيد تعيين التطبيق — أغلقه وافتحه من جديد',
  tapToEditEnergy: 'اضغط للتعديل',
  myAccount: 'حسابي',

  infoTab: 'معلومات',
  infoPageTitle: 'معلومات عن الباركنسون',
  assessmentTab: 'تقييم',
  assessmentPageTitle: 'تقييم الحالة',
  assessmentHoehnYahr: 'مقياس هون ويار المعدّل',
  assessmentSchwabEngland: 'مقياس شواب وإنغلاند',
  assessmentSubmit: 'احسب النتيجة',
  assessmentResult: 'نتيجتك',
  assessmentStage: 'المرحلة',
  assessmentScore: 'النتيجة',
  assessmentInterpretation: 'التفسير',
  assessmentReset: 'إعادة التقييم',
  assessmentYes: 'نعم',
  assessmentNo: 'لا',

  // ── Doctors Screen (Patient) ──────────────────────────────────────────────
  myDoctors: 'دكاترة',
  contactDoctor: 'تواصل مع دكتور',
  loadingDots: 'جاري التحميل...',
  doctorsAvailable: 'دكاترة متاحون',
  doctorsAvailableNow: 'دكاترة متاحون الآن للتواصل',
  searchDoctorPlaceholder: 'ابحث عن دكتور أو تخصص...',
  noDoctorsYet: 'لا يوجد دكاترة مسجلون بعد',
  addNewDoctor: 'إضافة طبيب جديد',
  myDoctorsChats: '💬 دكاترتي (بيني وبينهم شات)',
  otherDoctors: '🩺 دكاترة أخرى',
  chooseContactMethod: 'اختر طريقة التواصل',
  inAppChat: 'شات داخل التطبيق',
  inAppChatDesc: 'راسل الدكتور مباشرة من هنا',
  available: 'متاح',
  busy: 'مشغول',
  tapToOpenChat: 'اضغط لفتح الشات',
  contactNow: 'تواصل الآن',
  notAvailableNow: 'غير متاح حالياً',
  yrsExperience: 'سنة خبرة',
  noResults: 'لا توجد نتائج',

  // ── Doctor Chat Screen (Patient) ──────────────────────────────────────────
  chatIsLocal: 'الشات دلوقتي محلي — هيتربط بالسيرفر قريباً',
  writeMessage: 'اكتب رسالتك...',
  today: 'اليوم',
  sending: 'جاري الإرسال...',
  downloaded: 'تم التنزيل ✅',
  saved: 'تم الحفظ ✅',
  savedToGallery: 'تم حفظ الصورة في معرض الصور',
  fileSaved: 'تم حفظ الملف',
  downloadFailed: 'فشل التنزيل',
  storagePerm: 'مطلوب إذن الوصول للتخزين',
  exerciseAccessRequest: 'طلب صلاحية التمارين',
  exerciseAccessDesc: 'يريد الدكتور الوصول إلى خطة تمارينك وإدارتها.',
  accept: 'قبول',
  decline: 'رفض',
  accessGranted: 'تم منح الصلاحية ✓',
  failedToAccept: 'فشل قبول الطلب',
  sendFailed: 'فشل إرسال الرسالة',
  sendFileFailed: 'فشل إرسال الملف',
  galleryPerm: 'مطلوب إذن الوصول للصور',
  cameraPerm: 'مطلوب إذن الكاميرا',
  image: 'صورة',
  open: 'فتح',
  micPerm: 'مطلوب إذن الميكروفون',
  holdToRecord: 'اضغط مطولاً للتسجيل',
  voiceMessage: '🎙️ رسالة صوتية',
  recordFailed: 'فشل التسجيل',
  newMessageFrom: 'رسالة جديدة من',

  // ── Medication Note ───────────────────────────────────────────────────────
  myMedications: 'أدويتي',
  addMedication: 'إضافة دواء جديد 💊',
  medicationName: 'اسم الدواء *',
  medicationDose: 'الجرعة',
  medicationTime: 'الوقت * (مثال: 09:00)',
  medicationDays: 'الأيام',
  medicationNotes: 'ملاحظات (اختياري)',
  saveMedication: 'حفظ الدواء',
  savingMedication: 'جاري الحفظ...',
  noMedications: 'لا يوجد أدوية بعد',
  addMedHint: 'اضغط + لإضافة دواء جديد',
  deleteMedTitle: 'حذف الدواء',
  deleteMedConfirm: 'هل تريد حذف',
  deleteMedNote: 'سيتم إلغاء كل تذكيراته أيضاً.',
  notNow: 'لأ، إلغاء',
  yesDelete: 'نعم، احذفه',
  medicationNotif: 'إشعار 5 دقائق قبل + في الوقت',
  medicationNameRequired: 'يرجى إدخال اسم الدواء',
  medicationTimeFormat: 'الوقت لازم يكون بالصيغة دي: 09:00',
  medicationConnError: 'فشل الحفظ، تأكد من الاتصال بالإنترنت',
  medicationDeleteFailed: 'فشل الحذف',
  medicationNotAuthenticated: 'يرجى تسجيل الدخول أولاً',
  dayDaily: 'يومياً',
  daySat: 'السبت',
  daySun: 'الأحد',
  dayMon: 'الاثنين',
  dayTue: 'الثلاثاء',
  dayWed: 'الأربعاء',
  dayThu: 'الخميس',
  dayFri: 'الجمعة',

  // ── Auth extra ────────────────────────────────────────────────────────────
  signInFailed: 'فشل تسجيل الدخول، حاول مجدداً',
  signUpFailed: 'فشل إنشاء الحساب، حاول مجدداً',
  patientLogin: 'دخول المريض',
  doctorLogin: 'دخول الدكتور',
  patientAccount: 'حساب مريض',
  doctorAccount: 'حساب دكتور',
  patientSignUpBadge: 'تسجيل مريض',
  switchToDoctorRole: 'أنت دكتور؟ غيّر دورك',
  switchToPatientRole: 'أنت مريض؟ غيّر دورك',
  imageUploadFailed: 'فشل رفع الصورة، حاول مرة أخرى',
  // ── More screen ──────────────────────────────────────────────────────────
  energyLow: 'منخفضة',
  energyTodayQ: '⚡ كيف طاقتك النهارده؟',
  notNowBtn: 'مش دلوقتي 😅',
  doctorsLink: 'دكاترة',
  infoLink: 'معلومات',
  assessmentLink: 'تقييمي',
  docAssessmentResults: 'نتائج التقييم',
  docAssessmentTitle: 'أداة التقييم',
  docAssessmentSelectScale: 'اختر مقياس التقييم',
  docAssessmentHoehnDesc: 'يقيس مراحل المرض من 0 إلى 5',
  docAssessmentSchwabDesc: 'يقيس قدرة المريض على الأنشطة اليومية',
  docAssessmentPatientLabel: 'المريض',
  docAssessmentQuestion: 'السؤال',
  docAssessmentOf: 'من',
  docAssessmentNext: 'التالي',
  docAssessmentPrev: 'السابق',
  docAssessmentSeeResult: 'عرض النتيجة',
  docAssessmentSaveResult: 'حفظ النتيجة',
  docAssessmentSaved: 'تم حفظ نتيجة التقييم',
  docAssessmentSaveFailed: 'فشل في حفظ النتيجة',
  docAssessmentStageLabel: 'المرحلة',
  docAssessmentScoreLabel: 'النتيجة',
  docAssessmentPercentLabel: 'النسبة',
  docAssessmentNewAssessment: 'تقييم جديد',
  docMyAssessmentLink: 'تقييماتي',
  // ── Docpatient screen ────────────────────────────────────────────────────
  galleryPermissionRequired: 'مطلوب إذن الوصول للمعرض',
  imageSavedGallery: 'تم حفظ الصورة في معرض الصور',
  imageSaveFailed: 'فشل حفظ الصورة',
  fileSavedSuccess: 'تم حفظ الملف بنجاح',
  fileSaveFailed: 'فشل حفظ الملف',
  saveToGalleryBtn: '🖼️ حفظ في المعرض',
  chooseFolderBtn: '📁 اختر مجلد الحفظ',
  downloadTitle: 'تحميل',
  downloadSubtitle: 'اختر مكان الحفظ',
  couldNotOpenFile: 'تعذر فتح الملف',
  fileDefault: 'ملف',
  exerciseLibraryTab: '📚 المكتبة',
  assignedExercisesTab: '✅ المُعيَّنة',
  noExercisesCategory: 'لا توجد تمارين في هذه الفئة',
  exerciseAddedBadge: '✓ مُضاف',
  exerciseAddBadge: '+ إضافة',
  noExercisesAssigned: 'لا توجد تمارين مُعيَّنة بعد',
  descOptional: 'وصف (اختياري)',
  doctorEditRequest: '🩺 طلب تعديل من الدكتور',
  acceptRequest: '✅ قبول',
  rejectRequest: '❌ رفض',
  patientDefault: 'مريض',
  fileUploadFailed2: 'فشل رفع الملف، حاول مرة أخرى',
  deleteLabel: 'حذف',
  doctorDefault: 'الدكتور',
  imageMsgLabel: '📷 صورة',
  thanksAutoReply: 'شكراً على رسالتك، سأرد عليك في أقرب وقت ممكن 🙏',
  specialtyRequired: 'التخصص مطلوب',
  specialtyPlaceholder: 'مثال: طب نفسي، أطفال، قلب...',
  medNamePlaceholder: 'مثال: باراسيتامول',
  medDosePlaceholder: 'مثال: حبة واحدة — 500mg',
  medNotesPlaceholder: 'أي ملاحظات إضافية...',
  thanksMotivated: 'شكراً، متشجع! 💪',
  medReminder: '⏰ تذكير دواء قريب',
  medReminderSuffix: 'بعد 5 دقائق',
  medTimeNow: '💊 وقت الدواء الآن',
  medTimePrefix: 'حان وقت',

  // ── Doctor Role Choose ────────────────────────────────────────────────────
  docRoleTitle: 'من أنت؟',
  docRoleSubtitle: 'اختر دورك للمتابعة',
  docRoleDoctor: 'دكتور',
  docRoleDoctorSub: 'متابعة المرضى وإدارة التمارين',
  docRolePatient: 'مريض',
  docRolePatientSub: 'متابعة تمارينك وصحتك اليومية',
  docContinue: 'متابعة',

  // ── Doctor Home ───────────────────────────────────────────────────────────
  docGreeting: 'أهلاً، د.',
  docManagePatients: 'إدارة المرضى والطلبات',
  docActivePatients: 'مرضى مقبولون',
  docPendingRequests: 'طلبات انتظار',
  docTotal: 'إجمالي',
  docSearchPatient: 'ابحث عن مريض...',
  docAcceptedOnly: 'تظهر هنا محادثات المرضى المقبولين فقط',
  docNewRequest: 'طلب جديد',
  docChatOpen: 'شات مفتوح',
  docRequestedOn: 'طلب في',
  docPendingNeedsAccept: 'طلبات تحتاج قبول',
  docActivePatientsList: 'المرضى المقبولون',
  docNoPatients: 'لا يوجد مرضى بعد',
  docNoPatientsSubtitle: 'ستظهر طلبات المرضى هنا عند وصولها',
  docLoading: 'جاري التحميل...',
  docAllTab: 'الكل',
  docActiveTab: 'نشطون',
  docPendingTab: 'انتظار',
  docAcceptRequest: 'قبول الطلب',
  docAcceptBody: 'هل تريد قبول طلب',
  docAcceptBody2: 'وفتح شات معه؟',
  docAcceptNow: 'لأ دلوقتي',
  docConfirmAccept: 'قبول',
  docFemale: 'أنثى',
  docMale: 'ذكر',
  docNewRequestChip: 'طلب جديد',
  docYears: 'سنة',
  docPendingDate: 'طلب في',
  docPatientsList: 'المرضى المقبولون',
  docPendingSection: 'طلبات تحتاج قبول',
  docAcceptedSection: 'المرضى المقبولون',

  // ── Doctor Chat List ──────────────────────────────────────────────────────
  docChats: 'المحادثات',
  docUnreadMessages: 'رسالة غير مقروءة',
  docSearchChats: 'ابحث في المحادثات...',
  docNoChats: 'لا توجد محادثات بعد',
  docNoChatsSubtitle: 'المحادثات ستظهر هنا فقط للمرضى الذين قبلت طلباتهم',
  docActiveNow: 'نشط الآن',
  docOffline: 'غير متصل',
  docStartChat: 'ابدأ المحادثة الآن...',
  docUnreadOnly: 'تظهر هنا محادثات المرضى المقبولين فقط',

  // ── Doctor Patient Chat (Docpatient) ──────────────────────────────────────
  docWriteMessage: 'اكتب رسالة...',
  docToday: 'اليوم',
  docQuickReplies: ['كيف حالك اليوم؟', 'هل تناولت الدواء؟', 'ما هي الأعراض؟', 'لا داعي للقلق', 'يرجى المراجعة غداً'],
  docSendAttachment: 'إرسال مرفق',
  docCamera: 'كاميرا',
  docGallery: 'صور',
  docFile: 'ملف',
  docAccessRequestTitle: 'طلب صلاحية التمارين',
  docAccessRequestBody: 'طلب الدكتور إذنك لتعيين وإدارة التمارين الخاصة بك',
  docAccessPending: 'بانتظار رد المريض',
  docAccessApproved: 'تمت الموافقة على الطلب',
  docImageMsg: '🖼 صورة',
  docMsgSent: 'تم الإرسال',
  docMsgFailed: 'فشل الإرسال',
  docCameraPerm: 'مطلوب إذن الكاميرا',
  docGalleryPerm: 'مطلوب إذن المعرض',
  docFilePerm: 'فشل اختيار الملف',

  // ── Doctor Exercise Modal ─────────────────────────────────────────────────
  docExercisesTitle: 'تمارين',
  docExercisesSuffix: 'المريض',
  docExercisesLoading: 'جاري التحميل...',
  docExercisesCount: 'تمرين',
  docExercisesDone: 'تم',
  docPatientBaseExercises: '📋 تمارين المريض الأساسية',
  docDoctorExercises: '🩺 تمارين أضافها الدكتور',
  docExerciseCustom: 'مخصص',
  docExerciseDoneBadge: 'تم',
  docExerciseReadOnly: 'للقراءة فقط',
  docExercisePendingBadge: 'بانتظار القبول',
  docExerciseDoneBadgeFull: 'تم ✓',
  docExerciseProposed: '✏️ التعديل المقترح:',
  docExerciseNameLabel: 'الاسم:',
  docExerciseDurationLabel2: 'المدة:',
  docExerciseAttachment: 'مرفق',
  docNoExercisesSection: 'لا توجد تمارين في قسم',
  docAddExerciseBtn: 'أضف تمرين',
  docNewExerciseTitle: '➕ تمرين جديد',
  docAttachFile: 'إرفاق ملف أو صورة (اختياري)',
  docSavingDots: 'جاري...',
  docSaveBtn: 'حفظ',
  docCancelBtn: 'إلغاء',
  docEditExerciseTitle: '✏️ تعديل التمرين',
  docEditWarning: '⚠️ سيتم إرسال طلب تعديل للمريض، وسيُطبَّق التعديل بعد قبوله',
  docSendToPatient: 'إرسال للمريض',
  docSendingDots: 'جاري...',
  docDeleteExerciseTitle: 'حذف التمرين',
  docDeleteExerciseConfirm: 'هل تريد حذف',
  docEditRequestSent: '✅ تم إرسال طلب التعديل',
  docEditRequestSentBody: 'تم إرسال طلب التعديل للمريض',
  docEditRejected: '❌ رفض التعديل',
  docEditRejectedBody: 'المريض رفض تعديل تمرين',
  docExerciseNotice: 'تنبيه',
  docEnterExerciseName: 'أدخل اسم التمرين',
  docExerciseNameAr: 'اسم التمرين (عربي)',
  docExerciseNameEn: 'Exercise name (English)',
  docDescAr: 'وصف (عربي)',
  docDescEn: 'Description (English)',
  docEnterValidDuration: 'أدخل مدة صحيحة',
  docExerciseMin: 'دقيقة',
  docExercisesOf: 'تمارين',

  // ── Doctor More / Profile ─────────────────────────────────────────────────
  docPatientExercises: 'تمارين المريض',
  docAssignExercise: 'تعيين تمرين',
  docExerciseName: 'اسم التمرين *',
  docExerciseDuration: 'المدة (دقائق) *',
  docExerciseDesc: 'وصف (اختياري)',
  docExerciseEmoji: 'إيموجي',
  docSaveExercise: '✅ حفظ التمرين',
  docNoExercises: 'لم يتم تعيين تمارين بعد',
  docRemoveExercise: 'حذف التمرين',
  docExerciseAdded2: 'تم إضافة تمرين ✅',
  docExerciseRemoved: 'تم حذف التمرين 🗑️',
  docViewExercises: 'عرض التمارين',
  docOpenChat: 'فتح الشات',
  docMyAccount: 'حسابي',
  docDoctor: 'دكتور',
  docSpecialty: 'التخصص',
  docLicense: 'رقم الترخيص',
  docSpecialtyNotSet: 'التخصص غير محدد',
  docTotalPatients: 'إجمالي المرضى',
  docActivePatientsStat: 'مرضى نشطون',
  docSessions: 'الجلسات',
  docQuickLinksPatients: 'المرضى',
  docQuickLinksChats: 'الشاتات',
  docQuickLinksExercises: 'التمارين',
  docQuickLinksSessions: 'الجلسات',
  docQuickLinksAlerts: 'إشعارات',
  docPhotoSubtitle: 'صورة احترافية تعكس ثقتك! 🩺',
  docNotificationsTitle: 'إشعارات الدكتور',
  docNotifNewRequest: 'طلب مريض جديد 🆕',
  docNotifRequestAccepted: 'تم قبول مريض ✅',
  docNotifNewMessage: 'رسالة جديدة 💬',
  docNotifExerciseAssigned: 'تمرين مُعيَّن 🏋️',
  docNotifUnread: 'غير مقروءة',
  docNotifRead: 'مقروءة',
  docClearAll: 'مسح الكل',
  docNoNotifs: 'لا توجد إشعارات',
  docNoNotifsSubtitle: 'ستظهر هنا إشعارات المرضى والشات',
  docPatients: 'مرضى',
  docAccepted: 'مقبولون',
  docPending: 'انتظار',
  docPendingLabel: 'طلبات انتظار',
  docAcceptedLabel: 'مرضى مقبولون',
  docTotalLabel: 'إجمالي',
  docAccountInfo: 'معلومات الحساب',
  docQuickLinksSection: 'روابط سريعة',
  docInfoLink: 'معلومات الباركنسون',
  docMedicationInfo: 'معلومات الأدوية',
  docSettingsSection: 'الإعدادات',
  docLogout: 'تسجيل الخروج',
  docLogoutConfirm: 'هل أنت متأكد من تسجيل الخروج؟',
  docVersion: 'الإصدار 1.0.0',
  docSave: 'حفظ التعديلات',
  docSaving: 'جاري الحفظ…',
  docError: 'خطأ',
  docNameRequired: 'الاسم الأول والأخير مطلوبان',
  docSaveFailed: 'فشل الحفظ، حاول مجدداً',
  docEditProfileTitle: 'تعديل الملف الشخصي',
  docLanguage: 'اللغة',
  docLanguageAr: 'عربي',
  docLanguageEn: 'English',
  doctorsWord: 'دكتور',
  docTitlePrefix: 'د.',
  patientExercises: 'تمارين المريض',
  docHelp: 'المساعدة',
  docFaq1q: 'كيف أضيف مريضاً جديداً؟',
  docFaq1a: 'اذهب إلى قائمة المرضى واضغط على زر الإضافة.',
  docFaq2q: 'كيف أحدّث ملفي الشخصي؟',
  docFaq2a: 'اذهب إلى المزيد ← تعديل الملف الشخصي وحدّث بياناتك.',
  docFaq3q: 'كيف أتواصل مع فريق الدعم؟',
  docFaq3a: 'راسلنا على support@rahati.app وسنرد خلال 24 ساعة.',
  docLongPressHint: '👆 اضغط مطوّل لخيارات الصورة',
  docPhotoTitle: 'صورتك الشخصية',
  docChangePhoto: 'غيّر الصورة',
  docAddPhoto: 'أضف صورة',
  docDeletePhoto: 'احذف الصورة',
  docCancelPhoto: 'مش دلوقتي 😅',
  docProfileUpdated: 'تم تحديث الملف الشخصي',
  docPhotoPerm: 'مطلوب إذن الوصول للصور',
  docPhotoAdded: 'تم تحديث صورتك',
  docPhotoAddedBody: 'تم رفع صورتك الشخصية بنجاح 🎉',
  docPhotoDeleted: 'تم حذف الصورة',
  docPhotoDeletedBody: 'تم حذف صورتك الشخصية',
  docLoggedOut: 'تم تسجيل الخروج',
  docLoggedOutBody: 'تم تسجيل خروجك بنجاح. نراك قريباً!',
  docLangChanged: 'تم تغيير اللغة',
  docLangChangedAr: 'تم تفعيل اللغة العربية بنجاح',
  docLangChangedEn: 'English language has been activated',
  docSelectLanguage: 'اختر لغتك المفضلة',
  docLangCancel: 'إلغاء',

  // ── Doctor Notification Service ───────────────────────────────────────────
  docNotifNewRequestTitle: '🆕 طلب انضمام جديد',
  docNotifNewRequestBody: 'أرسل طلب انضمام',
  docNotifAcceptedTitle: '✅ تم قبول المريض',
  docNotifAcceptedBody: 'أصبح من مرضاك',
  docNotifMsgFromTitle: '💬 رسالة من',
  docNotifMsgSentTitle: '📤 رسالة أُرسلت لـ',
  docNotifProfileUpdatedTitle: '✏️ تم تحديث الملف الشخصي',
  docNotifProfileUpdatedBody: 'تم حفظ بياناتك بنجاح',
  docNotifLangChangedTitle: '🌐 تم تغيير اللغة',
  docNotifPhotoAddedTitle: '📸 تم تحديث صورتك',
  docNotifPhotoAddedBody: 'تم رفع صورتك الشخصية بنجاح 🎉',
  docNotifPhotoDeletedTitle: '🗑️ تم حذف الصورة',
  docNotifPhotoDeletedBody: 'تم حذف صورتك الشخصية',
  docNotifLogoutTitle: '👋 تم تسجيل الخروج',
  docNotifLogoutBody: 'تم تسجيل خروجك بنجاح. نراك قريباً!',

  // ── LangChoose Screen ─────────────────────────────────────────────────────
  langChooseTitle: 'اختر لغتك',
  langChooseSubtitle: 'يمكنك تغييرها لاحقاً من الإعدادات',
  langArabic: 'العربية',
  langEnglish: 'English',
  langContinue: 'متابعة',

  // ── Startup Screen ────────────────────────────────────────────────────────
  startupGreet: 'مرحباً بك في',
  startupTagline: 'رفيقك في إدارة طاقتك',
  startupTagline2: 'كل يوم خطوة نحو حياة',
  startupTagline3: 'أفضل 💜',
  startupBtn: 'ابدأ يومك',
  startupFooter: 'أجل رحلة بناء عاداتك اليومية وتحقيق طاقة حياتك',

  // ── Notification content ──────────────────────────────────────────────────
  taskDoneNotifTitle:     '✅ أحسنت! أكملت مهمة',
  exerciseDoneNotifTitle: '💪 انتهى التمرين!',
  exerciseDoneNotifBody:  'عمل رائع، واصل التميز! 🌟',
};

const EN: typeof AR = {
  // ── Auth ──────────────────────────────────────────────────────────────────
  appName: 'hekaya-haraka',
  appTagline: 'Your energy management companion',
  appTagline2: 'Your daily health & wellness buddy',
  signIn: 'Sign In',
  signUp: 'Create Account',
  email: 'Email Address',
  password: 'Password',
  confirmPassword: 'Confirm Password',
  noAccount: "Don't have an account?",
  haveAccount: 'Already have an account?',
  welcome: 'Welcome back 👋',
  orWith: 'Or continue with',
  google: 'Google',
  facebook: 'Facebook',
  continueBtn: 'Continue',
  startDay: 'Start Your Day',
  required: 'This field is required',
  invalidEmail: 'Invalid email address',
  shortPassword: 'Password must be at least 6 characters',
  passwordMismatch: 'Passwords do not match',
  invalidAge: 'Please enter a valid age',
  personalInfo: 'Personal Information',
  enterPersonalInfo: 'Enter your personal details',
  accountData: 'Account Data',
  createAccount: 'Create your account credentials',
  firstName: 'First Name',
  lastName: 'Last Name',
  age: 'Age',
  gender: 'Gender',
  male: 'Male',
  female: 'Female',
  step1of2: 'Step 1 of 2',
  step2of2: 'Step 2 of 2',
  welcomeTo: 'Welcome to hekaya-haraka',
  hello: 'Hello,',

  // ── Navigation / Tabs ─────────────────────────────────────────────────────
  home: 'Home',
  tasks: 'Tasks',
  exercisesTab: 'Exercises',
  more: 'More',
  meditation: 'Meditation',
  nutrition: 'Nutrition',
  exercises: 'Exercises',

  // ── Tasks Screen ──────────────────────────────────────────────────────────
  myTasks: 'My Tasks',
  completedOf: 'completed',
  from: 'of',
  todayProgress: "Today's Progress",
  all: 'All',
  work: 'Work',
  study: 'Study',
  atHome: 'Home',
  addTask: 'Add Task',
  taskTitle: 'Task Title',
  taskTime: 'Time',
  taskEnergy: 'Energy Cost (%)',
  taskCategory: 'Category',
  cancel: 'Cancel',
  add: 'Add',
  taskCoding: 'Computer Work',
  taskReading: 'Reading & Study',
  taskCooking: 'Cooking',
  taskCleaning: 'Cleaning & Tidying',
  taskType: 'Task Type',
  taskTypeCore: 'Core 🔁',
  taskTypeExtra: 'Extra ⚡ (Today only)',
  taskName: 'Task name *',
  taskIcon: 'Icon (emoji)',
  taskCategory2: 'Category',
  taskEnergyConsumed: 'Energy consumed (%)',
  taskNamePlaceholder: 'e.g. Read a book...',
  taskEnergyPlaceholder: 'e.g. 20',
  addNewTask: 'Add New Task',
  addTaskBtn: '✚ Add Task',
  taskOptions: 'Task Options',
  moveToExtra: '⚡ Move to Extra',
  moveToCore: '⭐ Move to Core',
  deleteTask: '🗑️ Delete',
  taskMoved: 'Task Moved ✅',
  taskMovedToCore: 'Core',
  taskMovedToExtra: 'Extra',
  taskDeleted: 'Task Deleted 🗑️',
  coreTasks: 'Core',
  extraTasks: 'Extra',
  coreTasksHint: 'Daily fixed tasks — long press for options',
  extraTasksHint: 'Extra tasks for today only — long press for options',
  noCoreTasksYet: 'No core tasks yet',
  noExtraTasksToday: 'No extra tasks for today',
  noTasksInCategory: 'No tasks in this category',
  saving: 'Saving...',
  taskTimeFrom: 'From',
  taskTimeTo: 'To',
  taskTimeFromPlaceholder: '09:00 AM',
  taskTimeToPlaceholder: '10:00 AM',
  taskNameRequired: 'Please enter task name',
  taskNameRequiredEn: 'Please enter task name',
  savingDots: 'Saving...',

  // ── Exercises Screen ──────────────────────────────────────────────────────
  todayExercises: "Today's Exercises",
  chooseExercise: 'Choose an exercise to start',
  startExercise: 'Start Exercise',
  timeRemaining: 'Time Remaining',
  exerciseDone: 'Well done! Exercise complete 🎉',
  pause: 'Pause',
  resume: 'Resume',
  stop: 'Stop',
  exerciseOptions: 'Exercise Options',
  moveExerciseToExtra: '⚡ Move to Extra',
  moveExerciseToCore: '⭐ Move to Core',
  addNewExercise: 'Add New Exercise',
  exerciseType: 'Exercise Type',
  exerciseEmoji: 'Emoji',
  exerciseNameLabel: 'Exercise name *',
  exerciseDurationLabel: 'Duration (minutes) *',
  exerciseDescLabel: 'Description (optional)',
  exerciseNamePlaceholder: 'e.g. Stair walking',
  exerciseDurationPlaceholder: 'e.g. 5',
  exerciseDescPlaceholder: 'Short description',
  saveExercise: '✅ Save Exercise',
  longPressForOptions: 'Long press for options',
  coreExercises: 'Core',
  extraExercises: 'Extra',
  coreExercisesHint: 'Daily fixed exercises — always available',
  extraExercisesHint: 'Extra exercises for today only',
  noCoreExercises: 'No core exercises yet',
  noExtraExercises: 'No extra exercises for today',
  addExercise: 'Add Exercise',
  stopExercise: 'End Exercise',
  startExerciseWithDuration: 'Start',
  readSteps: 'Read steps aloud',
  exerciseMoved: 'Exercise Moved ✅',
  exerciseDeleted: 'Exercise Deleted 🗑️',
  exerciseAdded: 'Exercise Added ✅',
  dailyExercises: "Today's Exercises",
  quickExercise: 'Quick Exercise',
  customExercise: '✨ Custom exercise',
  exerciseMinute: 'min',
  exerciseNoSection: 'No exercises in',
  exerciseNoSectionYet: 'yet',
  exerciseAddBtn: 'Add Exercise',
  exerciseSectionDesc_therapy: 'Physical & occupational therapy exercises',
  exerciseSectionDesc_yoga: 'Yoga poses & relaxation',
  exerciseSectionDesc_aerobic: 'Cardio & aerobic exercises',
  exerciseSectionDesc_endurance: 'Strength & endurance training',
  exerciseSectionDesc_strength: 'Muscle & joint strengthening exercises',
  exerciseSectionDesc_coordination: 'Motor coordination & balance exercises',
  doctorExercise: 'Dr.',
  exerciseDoneDr: 'Exercise Done ✓',
  exerciseTapWhenDone: 'Tap when done',
  startSession: 'Start Exercise',
  startDot: 'Start · ',
  stopReadSteps: 'Stop',

  // ── Exercise Session Screen ────────────────────────────────────────────────
  sessionRunning: 'Exercise session running',
  sessionPaused: 'Paused ⏸',
  sendAttachment: 'Send Attachment',
  camera: 'Camera',
  gallery: 'Gallery',
  file: 'File',
  muted: 'Muted 🔇',
  endExercise: 'End Exercise',
  wellDoneComplete: 'Well done! Exercise complete 🎉',

  // ── Home / Plan Screen ────────────────────────────────────────────────────
  myPlan: 'My Plan Today',
  notifications: 'Notifications',
  energyZero: 'Add tasks to see your energy level',
  energySufficient: "Your energy is sufficient for today's tasks",
  energyInsufficient: 'Your energy may not be enough for all tasks',
  organizedByEnergy: 'Your day is organized based\non your energy level of',
  noTasksToday: 'No tasks for this day',
  addTasksFromTasksPage: 'Add tasks from the Tasks page',
  allDone: '🎉 You completed all tasks today! Amazing!',
  done: 'Done',
  notDoneYet: 'Not done yet',
  notTimeYet: 'Not time yet',
  exercise: 'Exercise',
  doneLabel: '✅ Completed',
  lockedLabel: '⏳ Not time yet',
  energyWarning: 'Your energy may not be enough for this task',
  coreTasksCount: 'Core',
  extraTasksCount: 'Extra',
  exercisesCount: 'Exercises',
  calMonths: ['January','February','March','April','May','June','July','August','September','October','November','December'],
  calDays: ['Su','Mo','Tu','We','Th','Fr','Sa'],
  basicTask: '⭐ Core',
  extraTaskBadge: '⚡ Extra',
  quickExerciseBadge: 'Quick Exercise',
  noTasksDay: 'No tasks for this day',
  addTasksBtn: 'Add tasks from the Tasks page',
  energyOkLabel: "Your energy is sufficient for today's tasks",
  energyLowLabel: 'Your energy may not be enough for all tasks',
  planToday: 'My Plan Today',
  yesterday: 'Yesterday',
  completedCount: 'completed',
  pastDayViewMode: 'Viewing past record — editing not allowed',
  futureDayPlanMode: 'Future planning — tasks won\'t count until that day',
  planForDay: 'Plan tasks for this day',
  noTasksPastDay: 'No tasks recorded for this day',
  calFullDays: ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'],

  // ── Energy Screen ─────────────────────────────────────────────────────────
  myEnergyToday: 'My Energy Today',
  whatIsYourEnergy: 'What is your energy today?',
  chooseEnergyLevel: 'Choose your energy level for today',
  saveEnergy: 'Save Energy',
  energyExhausted: 'Exhausted',
  energyMedium: 'Medium',
  energyGood: 'Good',
  energyExcellent: 'Excellent',

  // ── Notifications ─────────────────────────────────────────────────────────
  notificationsTitle: 'Notifications',
  unread: 'Unread',
  read: 'Read',
  allRead: 'All notifications have been read ✅',
  noNotifications: 'No notifications',
  noNotificationsSubtitle: 'They will appear here when there are updates in the app',
  tapForDetails: 'Tap for details',
  okBtn: 'OK 👍',
  notifTypeTask: 'Task',
  notifTypeBreak: 'Break',
  notifTypeEnergy: 'Energy',
  notifTypeAdd: 'Added',
  notifTypeDelete: 'Deleted',
  notifTypeUpdate: 'Updated',
  taskNearTitle: 'Task coming up ⏰',
  exerciseNearTitle: 'Exercise coming up ⏰',
  taskNear10: 'starts in 10 minutes',
  taskNear5: 'starts in 5 minutes, get ready!',
  taskNowTitle: "It's task time! 🚀",
  exerciseNowTitle: "It's exercise time! 🚀",
  startNow: 'Start',
  nowLabel: 'now',
  missedTask: 'Missed task! 😔',
  missedExercise: 'Missed exercise! 😔',
  missedTaskBody: 'has passed and was not marked as done',
  taskCompleted: 'Well done! Task completed 🎉',
  taskCompletedBody: 'successfully! Keep up the progress 💪',
  exerciseCompleted: 'Exercise complete! 💪',
  exerciseCompletedBody: 'successfully! Your body thanks you 🌟',
  energyRaised: 'increased',
  energyLowered: 'decreased',
  energyLevelChanged: 'Energy level',
  energyNow: 'Your energy is now',
  taskAddedNotif: 'New task added ✅',
  taskAddedBody: 'was added to the plan',
  tasksAddedBody: 'tasks added to the plan',
  taskDeletedNotif: 'Task deleted 🗑️',
  tasksDeletedBody: 'tasks removed from the plan',
  dailyReminder: '🌿 Daily Reminder',
  dailyReminderBody: "Time to check today's tasks and exercises 💪",
  notifTaskNear10Body: 'starts in 10 minutes',
  notifTaskNear5Body: 'starts in 5 minutes, get ready!',
  notifTaskNowBody: 'Start',
  notifTaskLabel: 'task',
  notifExerciseLabel: 'exercise',
  notifMissedBody: 'has passed and was not marked as done',
  notifTaskCompletedTitle: 'Well done! Task completed 🎉',
  notifTaskCompletedBody: 'successfully! Keep up the progress 💪',
  notifExerciseCompletedTitle: 'Exercise complete! 💪',
  notifExerciseCompletedBody: 'successfully! Your body thanks you 🌟',
  notifEnergyRaised: 'increased',
  notifEnergyLowered: 'decreased',
  notifEnergyTitle: 'Energy level',
  notifEnergyBody: 'Your energy is now',
  appNotifications: '🔔 App Notifications',
  appNotificationsDesc: 'Enable or disable all app notifications',
  dailyReminderLabel: '⏰ Daily Task Reminder',
  dailyReminderDesc: 'Daily notification to review tasks and exercises',
  reminderTime: '🕐 Reminder Time',
  reminderTimeHint: "You'll get a notification every day at",
  serverNotifNote: 'Email notifications and app updates require a server connection and are not available yet.',
  saveSettings: '💾 Save Settings',

  // ── More / Profile Screen (Patient) ──────────────────────────────────────
  profile: 'Profile',
  accountInfo: 'Account Information',
  settings: 'Settings',
  editProfile: 'Edit Profile',
  language: 'Language',
  privacy: 'Privacy & Security',
  help: 'Help & Support',
  logout: 'Log Out',
  logoutConfirm: 'Are you sure you want to log out?',
  confirm: 'Confirm',
  version: 'Version 1.0.0',
  years: 'years',
  save: 'Save Changes',
  editProfileTitle: 'Edit Profile',
  error: 'Error',
  invalidCredential: 'Incorrect email or password',
  authError: 'An error occurred, please try again',
  userDataNotFound: 'User data not found, please try again',
  nameRequired: 'First and last name are required.',
  saveFailed: 'Failed to save. Try again.',
  savingProfile: 'Saving…',
  selectLanguage: 'Choose your preferred language',
  pushNotifications: 'Push Notifications',
  emailNotifications: 'Email Notifications',
  reminders: 'Reminders',
  appUpdates: 'App Updates',
  faq1q: 'How do I update my profile?',
  faq1a: 'Go to More → Edit Profile and update your information.',
  faq2q: 'How do I change the language?',
  faq2a: 'Go to More → Language and select your preferred language.',
  faq3q: 'How do I contact support?',
  faq3a: 'Email us at support@rahati.app and we\'ll reply within 24 hours.',
  photoPermissionRequired: 'Permission to access photos is required.',
  longPressHint: '👆 Long press for photo options',
  photoTitle: 'Profile Photo',
  photoSubtitle: 'Make it yours! 🌟',
  changePhoto: 'Change Photo',
  addPhoto: 'Add Photo',
  deletePhoto: 'Delete Photo',
  quickLinks: 'Quick Links',
  myPlanLink: 'My Plan',
  exercisesLink: 'Exercises',
  tasksLink: 'Tasks',
  alertsLink: 'Alerts',
  highEnergy: 'High Energy',
  mediumEnergy: 'Medium Energy',
  lowEnergy: 'Low Energy',
  generalSettings: 'General Settings',
  profileUpdated: 'Profile Updated ✅',
  profileUpdatedBody: 'Your profile has been updated successfully',
  notifPermError: 'Save failed, check notification permissions',
  resetApp: 'Reset App',
  resetDone: '✅ Done',
  resetMsg: 'App reset — close and reopen it',
  tapToEditEnergy: 'tap to edit',
  myAccount: 'Profile',

  infoTab: 'Info',
  infoPageTitle: "Parkinson's Disease Info",
  assessmentTab: 'Assessment',
  assessmentPageTitle: 'Health Assessment',
  assessmentHoehnYahr: 'Modified Hoehn & Yahr Scale',
  assessmentSchwabEngland: 'Schwab & England ADL Scale',
  assessmentSubmit: 'Calculate Result',
  assessmentResult: 'Your Result',
  assessmentStage: 'Stage',
  assessmentScore: 'Score',
  assessmentInterpretation: 'Interpretation',
  assessmentReset: 'Reassess',
  assessmentYes: 'Yes',
  assessmentNo: 'No',

  // ── Doctors Screen (Patient) ──────────────────────────────────────────────
  myDoctors: 'Doctors',
  contactDoctor: 'Contact a Doctor',
  loadingDots: 'Loading...',
  doctorsAvailable: 'doctors available',
  doctorsAvailableNow: 'doctors available now',
  searchDoctorPlaceholder: 'Search doctor or specialty...',
  noDoctorsYet: 'No doctors registered yet',
  addNewDoctor: 'Add New Doctor',
  myDoctorsChats: '💬 My Doctors (Active Chats)',
  otherDoctors: '🩺 Other Doctors',
  chooseContactMethod: 'Choose contact method',
  inAppChat: 'In-App Chat',
  inAppChatDesc: 'Message the doctor directly here',
  available: 'Available',
  busy: 'Busy',
  tapToOpenChat: 'Tap to open chat',
  contactNow: 'Contact Now',
  notAvailableNow: 'Not Available',
  yrsExperience: 'yrs exp',
  noResults: 'No results found',

  // ── Doctor Chat Screen (Patient) ──────────────────────────────────────────
  chatIsLocal: 'Chat is currently local — will connect to server soon',
  writeMessage: 'Write your message...',
  today: 'Today',
  sending: 'Sending...',
  downloaded: 'Downloaded ✅',
  saved: 'Saved ✅',
  savedToGallery: 'Image saved to gallery',
  fileSaved: 'File saved',
  downloadFailed: 'Download failed',
  storagePerm: 'Storage permission required',
  exerciseAccessRequest: 'Exercise Access Request',
  exerciseAccessDesc: 'The doctor is requesting access to manage your exercise plan.',
  accept: 'Accept',
  decline: 'Decline',
  accessGranted: 'Access Granted ✓',
  failedToAccept: 'Failed to accept request',
  sendFailed: 'Failed to send message',
  sendFileFailed: 'Failed to send file',
  galleryPerm: 'Gallery permission required',
  cameraPerm: 'Camera permission required',
  image: 'Image',
  open: 'Open',
  micPerm: 'Microphone permission required',
  holdToRecord: 'Hold to record',
  voiceMessage: '🎙️ Voice message',
  recordFailed: 'Recording failed',
  newMessageFrom: 'New message from',

  // ── Medication Note ───────────────────────────────────────────────────────
  myMedications: 'My Medications',
  addMedication: 'Add New Medication 💊',
  medicationName: 'Medication name *',
  medicationDose: 'Dose',
  medicationTime: 'Time * (e.g. 09:00)',
  medicationDays: 'Days',
  medicationNotes: 'Notes (optional)',
  saveMedication: 'Save Medication',
  savingMedication: 'Saving...',
  noMedications: 'No medications yet',
  addMedHint: 'Tap + to add a new medication',
  deleteMedTitle: 'Delete Medication',
  deleteMedConfirm: 'Do you want to delete',
  deleteMedNote: 'All its reminders will also be cancelled.',
  notNow: "No, cancel",
  yesDelete: 'Yes, delete',
  medicationNotif: 'Notification 5 min before + at time',
  medicationNameRequired: 'Please enter medication name',
  medicationTimeFormat: 'Time format should be: 09:00',
  medicationConnError: 'Save failed, check your internet connection',
  medicationDeleteFailed: 'Delete failed',
  medicationNotAuthenticated: 'Please sign in first',
  dayDaily: 'Daily',
  daySat: 'Sat',
  daySun: 'Sun',
  dayMon: 'Mon',
  dayTue: 'Tue',
  dayWed: 'Wed',
  dayThu: 'Thu',
  dayFri: 'Fri',

  // ── Auth extra ────────────────────────────────────────────────────────────
  signInFailed: 'Sign in failed, please try again',
  signUpFailed: 'Sign up failed, please try again',
  patientLogin: 'Patient Login',
  doctorLogin: 'Doctor Login',
  patientAccount: 'Patient Account',
  doctorAccount: 'Doctor Account',
  patientSignUpBadge: 'Patient Sign Up',
  switchToDoctorRole: 'Are you a doctor? Switch role',
  switchToPatientRole: 'Are you a patient? Switch role',
  imageUploadFailed: 'Image upload failed, try again',
  // ── More screen ──────────────────────────────────────────────────────────
  energyLow: 'Low',
  energyTodayQ: '⚡ How is your energy today?',
  notNowBtn: 'Not now 😅',
  doctorsLink: 'Doctors',
  infoLink: 'Info',
  assessmentLink: 'My Assessment',
  docAssessmentResults: 'Assessment Results',
  docAssessmentTitle: 'Assessment Tool',
  docAssessmentSelectScale: 'Choose Assessment Scale',
  docAssessmentHoehnDesc: 'Measures disease stages from 0 to 5',
  docAssessmentSchwabDesc: 'Measures patient ability in daily activities',
  docAssessmentPatientLabel: 'Patient',
  docAssessmentQuestion: 'Question',
  docAssessmentOf: 'of',
  docAssessmentNext: 'Next',
  docAssessmentPrev: 'Previous',
  docAssessmentSeeResult: 'See Result',
  docAssessmentSaveResult: 'Save Result',
  docAssessmentSaved: 'Assessment result saved',
  docAssessmentSaveFailed: 'Failed to save result',
  docAssessmentStageLabel: 'Stage',
  docAssessmentScoreLabel: 'Score',
  docAssessmentPercentLabel: 'Percentage',
  docAssessmentNewAssessment: 'New Assessment',
  docMyAssessmentLink: 'My Assessments',
  // ── Docpatient screen ────────────────────────────────────────────────────
  galleryPermissionRequired: 'Gallery permission required',
  imageSavedGallery: 'Image saved to gallery',
  imageSaveFailed: 'Failed to save image',
  fileSavedSuccess: 'File saved successfully',
  fileSaveFailed: 'Failed to save file',
  saveToGalleryBtn: '🖼️ Save to Gallery',
  chooseFolderBtn: '📁 Choose Folder',
  downloadTitle: 'Download',
  downloadSubtitle: 'Choose where to save',
  couldNotOpenFile: 'Could not open file',
  fileDefault: 'File',
  exerciseLibraryTab: '📚 Library',
  assignedExercisesTab: '✅ Assigned',
  noExercisesCategory: 'No exercises in this category',
  exerciseAddedBadge: '✓ Added',
  exerciseAddBadge: '+ Add',
  noExercisesAssigned: 'No exercises assigned yet',
  descOptional: 'Description (optional)',
  doctorEditRequest: '🩺 Doctor Edit Request',
  acceptRequest: '✅ Accept',
  rejectRequest: '❌ Reject',
  patientDefault: 'Patient',
  fileUploadFailed2: 'File upload failed, try again',
  deleteLabel: 'Delete',
  doctorDefault: 'Doctor',
  imageMsgLabel: '📷 Image',
  thanksAutoReply: 'Thank you for your message, I will reply as soon as possible 🙏',
  specialtyRequired: 'Specialty is required',
  specialtyPlaceholder: 'e.g. Psychiatry, Cardiology...',
  medNamePlaceholder: 'e.g. Paracetamol',
  medDosePlaceholder: 'e.g. One tablet — 500mg',
  medNotesPlaceholder: 'Any additional notes...',
  thanksMotivated: 'Thanks, motivated! 💪',
  medReminder: '⏰ Medication Reminder',
  medReminderSuffix: 'in 5 minutes',
  medTimeNow: '💊 Medication Time',
  medTimePrefix: 'Time for',

  // ── Doctor Role Choose ────────────────────────────────────────────────────
  docRoleTitle: 'Who are you?',
  docRoleSubtitle: 'Choose your role to continue',
  docRoleDoctor: 'Doctor',
  docRoleDoctorSub: 'Follow up with patients & manage exercises',
  docRolePatient: 'Patient',
  docRolePatientSub: 'Track your exercises & daily health',
  docContinue: 'Continue',

  // ── Doctor Home ───────────────────────────────────────────────────────────
  docGreeting: 'Hello, Dr.',
  docManagePatients: 'Manage patients & requests',
  docActivePatients: 'Accepted Patients',
  docPendingRequests: 'Pending Requests',
  docTotal: 'Total',
  docSearchPatient: 'Search patient...',
  docAcceptedOnly: "Only accepted patients' chats appear here",
  docNewRequest: 'New Request',
  docChatOpen: 'Chat open',
  docRequestedOn: 'Requested on',
  docPendingNeedsAccept: 'Requests needing approval',
  docActivePatientsList: 'Accepted Patients',
  docNoPatients: 'No patients yet',
  docNoPatientsSubtitle: 'Patient requests will appear here when received',
  docLoading: 'Loading...',
  docAllTab: 'All',
  docActiveTab: 'Active',
  docPendingTab: 'Pending',
  docAcceptRequest: 'Accept Request',
  docAcceptBody: 'Do you want to accept the request from',
  docAcceptBody2: 'and open a chat?',
  docAcceptNow: 'Not now',
  docConfirmAccept: 'Accept',
  docFemale: 'Female',
  docMale: 'Male',
  docNewRequestChip: 'New Request',
  docYears: 'years',
  docPendingDate: 'Requested on',
  docPatientsList: 'Accepted Patients',
  docPendingSection: 'Requests needing approval',
  docAcceptedSection: 'Accepted Patients',

  // ── Doctor Chat List ──────────────────────────────────────────────────────
  docChats: 'Chats',
  docUnreadMessages: 'unread messages',
  docSearchChats: 'Search chats...',
  docNoChats: 'No chats yet',
  docNoChatsSubtitle: 'Chats will appear here only for accepted patients',
  docActiveNow: 'Active now',
  docOffline: 'Offline',
  docStartChat: 'Start a conversation now...',
  docUnreadOnly: 'Only accepted patients chats appear here',

  // ── Doctor Patient Chat (Docpatient) ──────────────────────────────────────
  docWriteMessage: 'Write a message...',
  docToday: 'Today',
  docQuickReplies: ['How are you today?', 'Did you take your medicine?', 'What are the symptoms?', 'No need to worry', 'Please come in tomorrow'],
  docSendAttachment: 'Send Attachment',
  docCamera: 'Camera',
  docGallery: 'Gallery',
  docFile: 'File',
  docAccessRequestTitle: 'Exercise Access Request',
  docAccessRequestBody: 'The doctor is requesting access to assign and manage your exercises',
  docAccessPending: 'Waiting for patient response',
  docAccessApproved: 'Request Approved',
  docImageMsg: '🖼 Image',
  docMsgSent: 'Message sent',
  docMsgFailed: 'Failed to send',
  docCameraPerm: 'Camera permission required',
  docGalleryPerm: 'Gallery permission required',
  docFilePerm: 'Failed to pick file',

  // ── Doctor Exercise Modal ─────────────────────────────────────────────────
  docExercisesTitle: 'Exercises',
  docExercisesSuffix: "Patient's",
  docExercisesLoading: 'Loading...',
  docExercisesCount: 'exercises',
  docExercisesDone: 'done',
  docPatientBaseExercises: "📋 Patient's Base Exercises",
  docDoctorExercises: '🩺 Doctor-Assigned Exercises',
  docExerciseCustom: 'Custom',
  docExerciseDoneBadge: 'Done',
  docExerciseReadOnly: 'Read only',
  docExercisePendingBadge: 'Pending',
  docExerciseDoneBadgeFull: 'Done ✓',
  docExerciseProposed: '✏️ Proposed edit:',
  docExerciseNameLabel: 'Name:',
  docExerciseDurationLabel2: 'Duration:',
  docExerciseAttachment: 'Attachment',
  docNoExercisesSection: 'No exercises in',
  docAddExerciseBtn: 'Add Exercise',
  docNewExerciseTitle: '➕ New Exercise',
  docAttachFile: 'Attach file or image (optional)',
  docSavingDots: 'Saving...',
  docSaveBtn: 'Save',
  docCancelBtn: 'Cancel',
  docEditExerciseTitle: '✏️ Edit Exercise',
  docEditWarning: '⚠️ An edit request will be sent to the patient and applied after their approval',
  docSendToPatient: 'Send to Patient',
  docSendingDots: 'Sending...',
  docDeleteExerciseTitle: 'Delete Exercise',
  docDeleteExerciseConfirm: 'Delete',
  docEditRequestSent: '✅ Edit Request Sent',
  docEditRequestSentBody: 'Edit request sent to patient for approval',
  docEditRejected: '❌ Edit Rejected',
  docEditRejectedBody: 'Patient rejected the edit for',
  docExerciseNotice: 'Notice',
  docEnterExerciseName: 'Enter exercise name',
  docExerciseNameAr: 'Exercise name (Arabic)',
  docExerciseNameEn: 'Exercise name (English)',
  docDescAr: 'Description (Arabic)',
  docDescEn: 'Description (English)',
  docEnterValidDuration: 'Enter a valid duration',
  docExerciseMin: 'min',
  docExercisesOf: 'exercises',

  // ── Doctor More / Profile ─────────────────────────────────────────────────
  docPatientExercises: 'Patient Exercises',
  docAssignExercise: 'Assign Exercise',
  docExerciseName: 'Exercise name *',
  docExerciseDuration: 'Duration (minutes) *',
  docExerciseDesc: 'Description (optional)',
  docExerciseEmoji: 'Emoji',
  docSaveExercise: '✅ Save Exercise',
  docNoExercises: 'No exercises assigned yet',
  docRemoveExercise: 'Remove Exercise',
  docExerciseAdded2: 'Exercise Added ✅',
  docExerciseRemoved: 'Exercise Removed 🗑️',
  docViewExercises: 'View Exercises',
  docOpenChat: 'Open Chat',
  docMyAccount: 'Profile',
  docDoctor: 'Doctor',
  docSpecialty: 'Specialty',
  docLicense: 'License Number',
  docSpecialtyNotSet: 'Specialty not set',
  docTotalPatients: 'Total Patients',
  docActivePatientsStat: 'Active Patients',
  docSessions: 'Sessions',
  docQuickLinksPatients: 'Patients',
  docQuickLinksChats: 'Chats',
  docQuickLinksExercises: 'Exercises',
  docQuickLinksSessions: 'Sessions',
  docQuickLinksAlerts: 'Alerts',
  docPhotoSubtitle: 'Professional photo that reflects your confidence! 🩺',
  docNotificationsTitle: 'Doctor Notifications',
  docNotifNewRequest: 'New Patient Request 🆕',
  docNotifRequestAccepted: 'Patient Accepted ✅',
  docNotifNewMessage: 'New Message 💬',
  docNotifExerciseAssigned: 'Exercise Assigned 🏋️',
  docNotifUnread: 'Unread',
  docNotifRead: 'Read',
  docClearAll: 'Clear All',
  docNoNotifs: 'No notifications',
  docNoNotifsSubtitle: 'Patient and chat notifications will appear here',
  docPatients: 'patients',
  docAccepted: 'accepted',
  docPending: 'pending',
  docPendingLabel: 'Pending Requests',
  docAcceptedLabel: 'Accepted Patients',
  docTotalLabel: 'Total',
  docAccountInfo: 'Account Information',
  docQuickLinksSection: 'Quick Links',
  docInfoLink: "Parkinson's Info",
  docMedicationInfo: 'Medication Info',
  docSettingsSection: 'Settings',
  docLogout: 'Log Out',
  docLogoutConfirm: 'Are you sure you want to log out?',
  docVersion: 'Version 1.0.0',
  docSave: 'Save Changes',
  docSaving: 'Saving…',
  docError: 'Error',
  docNameRequired: 'First and last name are required',
  docSaveFailed: 'Save failed, please try again',
  docEditProfileTitle: 'Edit Profile',
  docLanguage: 'Language',
  docLanguageAr: 'عربي',
  docLanguageEn: 'English',
  doctorsWord: 'doctors',
  docTitlePrefix: 'Dr.',
  patientExercises: "Patient's Exercises",
  docHelp: 'Help',
  docFaq1q: 'How do I add a new patient?',
  docFaq1a: 'Go to the patients list and press the add button.',
  docFaq2q: 'How do I update my profile?',
  docFaq2a: 'Go to More → Edit Profile and update your info.',
  docFaq3q: 'How do I contact support?',
  docFaq3a: 'Email us at support@rahati.app — we reply within 24h.',
  docLongPressHint: '👆 Long press for photo options',
  docPhotoTitle: 'Profile Photo',
  docChangePhoto: 'Change Photo',
  docAddPhoto: 'Add Photo',
  docDeletePhoto: 'Delete Photo',
  docCancelPhoto: 'Not now 😅',
  docProfileUpdated: 'Profile Updated',
  docPhotoPerm: 'Photo permission required',
  docPhotoAdded: 'Photo Updated',
  docPhotoAddedBody: 'Your profile photo has been uploaded successfully 🎉',
  docPhotoDeleted: 'Photo Deleted',
  docPhotoDeletedBody: 'Your profile photo has been deleted',
  docLoggedOut: 'Logged Out',
  docLoggedOutBody: 'You have been logged out successfully. See you soon!',
  docLangChanged: 'Language Changed',
  docLangChangedAr: 'Arabic language has been activated',
  docLangChangedEn: 'English language has been activated',
  docSelectLanguage: 'Choose your preferred language',
  docLangCancel: 'Cancel',

  // ── Doctor Notification Service ───────────────────────────────────────────
  docNotifNewRequestTitle: '🆕 New Join Request',
  docNotifNewRequestBody: 'sent a join request',
  docNotifAcceptedTitle: '✅ Patient Accepted',
  docNotifAcceptedBody: 'is now your patient',
  docNotifMsgFromTitle: '💬 Message from',
  docNotifMsgSentTitle: '📤 Message sent to',
  docNotifProfileUpdatedTitle: '✏️ Profile Updated',
  docNotifProfileUpdatedBody: 'Your data has been saved successfully',
  docNotifLangChangedTitle: '🌐 Language Changed',
  docNotifPhotoAddedTitle: '📸 Photo Updated',
  docNotifPhotoAddedBody: 'Your profile photo has been uploaded successfully 🎉',
  docNotifPhotoDeletedTitle: '🗑️ Photo Deleted',
  docNotifPhotoDeletedBody: 'Your profile photo has been deleted',
  docNotifLogoutTitle: '👋 Logged Out',
  docNotifLogoutBody: 'You have been logged out successfully. See you soon!',

  // ── LangChoose Screen ─────────────────────────────────────────────────────
  langChooseTitle: 'Choose Your Language',
  langChooseSubtitle: 'You can change it later from settings',
  langArabic: 'العربية',
  langEnglish: 'English',
  langContinue: 'Continue',

  // ── Startup Screen ────────────────────────────────────────────────────────
  startupGreet: 'Welcome to',
  startupTagline: 'Your energy management companion',
  startupTagline2: 'Every day a step toward a',
  startupTagline3: 'better life 💜',
  startupBtn: 'Start Your Day',
  startupFooter: 'Build your daily habits and achieve your energy goals',

  // ── Notification content ──────────────────────────────────────────────────
  taskDoneNotifTitle:     '✅ Great job! Task completed',
  exerciseDoneNotifTitle: '💪 Exercise session done!',
  exerciseDoneNotifBody:  'Keep it up, you\'re doing great! 🌟',
};

interface LangContextType {
  lang: Lang;
  t: typeof AR;
  setLang: (l: Lang) => void;
  isRTL: boolean;
}

const LangContext = createContext<LangContextType | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>('ar');

  useEffect(() => {
    AsyncStorage.getItem(LANG_KEY).then(saved => {
      if (saved === 'ar' || saved === 'en') setLangState(saved);
    }).catch(() => {});
  }, []);

  const setLang = useCallback((l: Lang) => {
    setLangState(l);
    AsyncStorage.setItem(LANG_KEY, l).catch(() => {});
    const uid = auth.currentUser?.uid;
    if (uid) setDoc(doc(db, 'users', uid), { lang: l }, { merge: true }).catch(() => {});
  }, []);

  const t = lang === 'ar' ? AR : EN;
  const isRTL = lang === 'ar';

  return (
    <LangContext.Provider value={{ lang, t, setLang, isRTL }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  const ctx = useContext(LangContext);
  if (!ctx) throw new Error('useLang must be inside LanguageProvider');
  return ctx;
}