// context/LanguageContext.tsx
import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Lang = 'ar' | 'en';

const AR = {
  // Auth
  appName: 'راحتي',
  appTagline: 'رفيقك في إدارة طاقتك',
  appTagline2: 'رفيقك اليومي للصحة والعافية',
  signIn: 'تسجيل الدخول',
  signUp: 'إنشاء حساب',
  email: 'البريد الإلكتروني',
  password: 'كلمة المرور',
  confirmPassword: 'تأكيد كلمة المرور',
  noAccount: 'ليس لديك حساب؟',
  haveAccount: 'لديك حساب بالفعل؟',
  welcome: 'أهلاً بعودتك 👋',
  orWith: 'أو تابع بواسطة',
  google: 'جوجل',
  facebook: 'فيسبوك',
  continueBtn: 'متابعة',
  startDay: 'ابدأ يومك',
  required: 'هذا الحقل مطلوب',
  invalidEmail: 'البريد الإلكتروني غير صحيح',
  shortPassword: 'كلمة المرور 6 أحرف على الأقل',
  passwordMismatch: 'كلمتا المرور غير متطابقتين',
  invalidAge: 'يرجى إدخال عمر صحيح',
  // Sign-up
  personalInfo: 'المعلومات الشخصية',
  enterPersonalInfo: 'أدخل معلوماتك الشخصية',
  accountData: 'بيانات الحساب',
  createAccount: 'أنشئ بيانات حسابك',
  firstName: 'الاسم الأول',
  lastName: 'الاسم الثاني',
  age: 'العمر',
  gender: 'الجنس',
  male: 'ذكر',
  female: 'أنثى',
  step1of2: 'الخطوة 1 من 2',
  step2of2: 'الخطوة 2 من 2',
  // Startup
  welcomeTo: 'مرحباً بك في راحتي',
  hello: 'مرحباً،',
  meditation: 'تأمل',
  nutrition: 'تغذية',
  exercises: 'تمارين',
  // Tabs
  home: 'الرئيسية',
  tasks: 'مهامي',
  exercisesTab: 'تمارين',
  more: 'المزيد',
  // Tasks screen
  myTasks: 'مهامي',
  completedOf: 'مكتملة',
  from: 'من',
  todayProgress: 'تقدمك اليوم',
  all: 'الكل',
  work: 'عمل',
  study: 'دراسة',
  atHome: 'منزل',
  addTask: 'إضافة مهمة',
  taskTitle: 'عنوان المهمة',
  taskTime: 'الوقت',
  taskEnergy: 'استهلاك الطاقة (%)',
  taskCategory: 'التصنيف',
  cancel: 'إلغاء',
  add: 'إضافة',
  taskCoding: 'العمل على الكمبيوتر',
  taskReading: 'القراءة والمطالعة',
  taskCooking: 'الطبخ والإعداد',
  taskCleaning: 'التنظيف والترتيب',
  // Exercises
  todayExercises: 'تمارين اليوم',
  chooseExercise: 'اختر تمريناً لتبدأ',
  startExercise: 'ابدأ التمرين',
  timeRemaining: 'الوقت المتبقي',
  exerciseDone: 'أحسنت! اكتمل التمرين 🎉',
  pause: 'إيقاف مؤقت',
  resume: 'استمرار',
  stop: 'إيقاف',
  // Home (Food)
  goodMorning: 'صباح الخير 🌿',
  foodFactors: 'الأكل والعوامل المؤثرة',
  todayTip: 'نصيحة اليوم',
  tipText: 'تناول وجبة غنية بالخضروات والبروتين لتعزيز طاقتك خلال اليوم.',
  usefulFoods: 'الأطعمة المفيدة',
  usefulSub: 'مفيدة لصحتك',
  symptomTriggers: 'محفزات الأعراض',
  triggerSub: 'تجنبها قدر الإمكان',
  vegetables: 'خضروات',
  fruits: 'فواكه',
  nuts: 'مكسرات',
  fish: 'سمك',
  heat: 'حرارة عالية',
  caffeine: 'كافيين',
  sugars: 'سكريات',
  fatty: 'أطعمة دهنية',
  // More / Profile
  profile: 'الملف الشخصي',
  accountInfo: 'معلومات الحساب',
  settings: 'الإعدادات',
  editProfile: 'تعديل الملف الشخصي',
  notifications: 'الإشعارات',
  language: 'اللغة',
  privacy: 'الخصوصية والأمان',
  help: 'المساعدة والدعم',
  logout: 'تسجيل الخروج',
  logoutConfirm: 'هل أنت متأكد أنك تريد الخروج؟',
  confirm: 'تأكيد',
  version: 'الإصدار 1.0.0',
  years: 'سنة',
  save: 'حفظ التغييرات',
  editProfileTitle: 'تعديل الملف الشخصي',
  error: 'خطأ',
  nameRequired: 'الاسم الأول والأخير مطلوبان.',
  saveFailed: 'فشل الحفظ. حاول مجدداً.',
  saving: 'جارٍ الحفظ…',
  selectLanguage: 'اختر لغتك المفضلة',
  pushNotifications: 'الإشعارات الفورية',
  emailNotifications: 'إشعارات البريد الإلكتروني',
  reminders: 'التذكيرات',
  appUpdates: 'تحديثات التطبيق',
  faq1q: 'كيف أحدّث ملفي الشخصي؟',
  faq1a: 'اذهب إلى المزيد ← تعديل الملف الشخصي وحدّث معلوماتك.',
  faq2q: 'كيف أغيّر اللغة؟',
  faq2a: 'اذهب إلى المزيد ← اللغة واختر لغتك المفضلة.',
  faq3q: 'كيف أتواصل مع الدعم؟',
  faq3a: 'راسلنا على support@rahati.app وسنرد خلال 24 ساعة.',
  photoPermissionRequired: 'يجب منح إذن الوصول إلى الصور.',
  // Avatar action sheet
  longPressHint: '👆 اضغط مطوّل لخيارات الصورة',
  photoTitle: 'صورتك الشخصية',
  photoSubtitle: 'خليها تعبّر عنك! 🌟',
  changePhoto: 'غيّر الصورة',
  addPhoto: 'أضف صورة',
  deletePhoto: 'احذف الصورة',
};

const EN: typeof AR = {
  appName: 'Rahati',
  appTagline: 'Your energy management companion',
  appTagline2: 'Your daily health & wellness buddy',
  signIn: 'Sign In',
  signUp: 'Create Account',
  email: 'Email Address',
  password: 'Password',
  confirmPassword: 'Confirm Password',
  noAccount: "Don't have an account?",
  haveAccount: 'Already have an account?',
  welcome: 'Welcome back 👋',
  orWith: 'Or continue with',
  google: 'Google',
  facebook: 'Facebook',
  continueBtn: 'Continue',
  startDay: 'Start Your Day',
  required: 'This field is required',
  invalidEmail: 'Invalid email address',
  shortPassword: 'Password must be at least 6 characters',
  passwordMismatch: 'Passwords do not match',
  invalidAge: 'Please enter a valid age',
  personalInfo: 'Personal Information',
  enterPersonalInfo: 'Enter your personal details',
  accountData: 'Account Data',
  createAccount: 'Create your account credentials',
  firstName: 'First Name',
  lastName: 'Last Name',
  age: 'Age',
  gender: 'Gender',
  male: 'Male',
  female: 'Female',
  step1of2: 'Step 1 of 2',
  step2of2: 'Step 2 of 2',
  welcomeTo: 'Welcome to Rahati',
  hello: 'Hello,',
  meditation: 'Meditation',
  nutrition: 'Nutrition',
  exercises: 'Exercises',
  home: 'Home',
  tasks: 'Tasks',
  exercisesTab: 'Exercises',
  more: 'More',
  myTasks: 'My Tasks',
  completedOf: 'completed',
  from: 'of',
  todayProgress: "Today's Progress",
  all: 'All',
  work: 'Work',
  study: 'Study',
  atHome: 'Home',
  addTask: 'Add Task',
  taskTitle: 'Task Title',
  taskTime: 'Time',
  taskEnergy: 'Energy Cost (%)',
  taskCategory: 'Category',
  cancel: 'Cancel',
  add: 'Add',
  taskCoding: 'Computer Work',
  taskReading: 'Reading & Study',
  taskCooking: 'Cooking',
  taskCleaning: 'Cleaning & Tidying',
  todayExercises: "Today's Exercises",
  chooseExercise: 'Choose an exercise to start',
  startExercise: 'Start Exercise',
  timeRemaining: 'Time Remaining',
  exerciseDone: 'Well done! Exercise complete 🎉',
  pause: 'Pause',
  resume: 'Resume',
  stop: 'Stop',
  goodMorning: 'Good Morning 🌿',
  foodFactors: 'Food & Influencing Factors',
  todayTip: "Today's Tip",
  tipText: 'Eat a meal rich in vegetables and protein to boost your energy throughout the day.',
  usefulFoods: 'Beneficial Foods',
  usefulSub: 'Good for your health',
  symptomTriggers: 'Symptom Triggers',
  triggerSub: 'Avoid when possible',
  vegetables: 'Vegetables',
  fruits: 'Fruits',
  nuts: 'Nuts',
  fish: 'Fish',
  heat: 'High Heat',
  caffeine: 'Caffeine',
  sugars: 'Sugars',
  fatty: 'Fatty Foods',
  profile: 'Profile',
  accountInfo: 'Account Information',
  settings: 'Settings',
  editProfile: 'Edit Profile',
  notifications: 'Notifications',
  language: 'Language',
  privacy: 'Privacy & Security',
  help: 'Help & Support',
  logout: 'Log Out',
  logoutConfirm: 'Are you sure you want to log out?',
  confirm: 'Confirm',
  version: 'Version 1.0.0',
  years: 'years',
  save: 'Save Changes',
  editProfileTitle: 'Edit Profile',
  error: 'Error',
  nameRequired: 'First and last name are required.',
  saveFailed: 'Failed to save. Try again.',
  saving: 'Saving…',
  selectLanguage: 'Choose your preferred language',
  pushNotifications: 'Push Notifications',
  emailNotifications: 'Email Notifications',
  reminders: 'Reminders',
  appUpdates: 'App Updates',
  faq1q: 'How do I update my profile?',
  faq1a: 'Go to More → Edit Profile and update your information.',
  faq2q: 'How do I change the language?',
  faq2a: 'Go to More → Language and select your preferred language.',
  faq3q: 'How do I contact support?',
  faq3a: "Email us at support@rahati.app and we'll reply within 24 hours.",
  photoPermissionRequired: 'Permission to access photos is required.',
  // Avatar action sheet
  longPressHint: '👆 Long press for photo options',
  photoTitle: 'Profile Photo',
  photoSubtitle: 'Make it yours! 🌟',
  changePhoto: 'Change Photo',
  addPhoto: 'Add Photo',
  deletePhoto: 'Delete Photo',
};

interface LangContextType {
  lang: Lang;
  t: typeof AR;
  setLang: (l: Lang) => void;
  isRTL: boolean;
}

const LangContext = createContext<LangContextType | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>('ar');
  const t = lang === 'ar' ? AR : EN;
  const isRTL = lang === 'ar';
  return (
    <LangContext.Provider value={{ lang, t, setLang, isRTL }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  const ctx = useContext(LangContext);
  if (!ctx) throw new Error('useLang must be inside LanguageProvider');
  return ctx;
}