// utils/defaultExercises.ts
// Single source of truth for all built-in exercise data.
// Imported by exercises.tsx (patient view) and Docpatient.tsx (doctor assign).

export type ExSectionKey = 'therapy' | 'yoga' | 'aerobic' | 'endurance' | 'strength' | 'coordination';
export type AnimType = 'hipMarch' | 'armRaise' | 'standingRow' | 'legCurl' | 'rollUp' | 'achillesRelease' | 'bounce' | 'sway';

export type DefaultExercise = {
  key: string;
  emoji: string;
  titleAr: string;
  titleEn: string;
  durationMin: number;
  durationSeconds: number;
  color: string;
  bg: string;
  accent: string;
  descAr: string;
  descEn: string;
  steps: string[];
  stepsEn: string[];
  animType: AnimType;
  type: ExSectionKey;
};

export const ALL_DEFAULT_EXERCISES: DefaultExercise[] = [
  // ─── Therapy ──────────────────────────────────────────────
  {
    key: 'wristCurls',
    emoji: '🤲',
    titleAr: 'ثني الرسغ (Wrist Curls)',
    titleEn: 'Wrist Curls',
    durationMin: 5, durationSeconds: 300,
    color: '#5B9BD5', bg: '#E8F1FB', accent: '#D0E5F7',
    descAr: 'يزيد الثبات، ويقلل الرعشة، ويحسّن خفة حركة الأصابع واليدين',
    descEn: 'Increases stability, reduces tremors, and improves finger and hand dexterity',
    steps: [
      'استخدم دمبل بوزن من 1 إلى 5 أرطال (0.5 إلى 2.5 كجم)',
      'ضع يدك اليسرى ورسغك على حافة طاولة مع توجيه راحة اليد للأعلى',
      'امسك الوزن في يدك بإحكام',
      'ارفع الرسغ ببطء لأعلى قدر تستطيع',
      'حافظ على الوضعية لبضع ثوانٍ ثم أنزل ببطء',
      'اعمل من 1 إلى 2 مجموعة، كل مجموعة 12 تكراراً، ثم كرر على اليد اليمنى',
    ],
    stepsEn: [
      'Use a dumbbell weighing 1 to 5 pounds (0.5 to 2.5 kg)',
      'Place your left hand and wrist on the edge of a table with your palm facing up',
      'Hold the weight firmly in your hand',
      'Slowly raise your wrist upward as far as you can',
      'Hold the position for a few seconds then lower slowly',
      'Do 1 to 2 sets of 12 repetitions, then repeat with the right hand',
    ],
    animType: 'armRaise', type: 'therapy',
  },

  // ─── Yoga ─────────────────────────────────────────────────
  {
    key: 'childsPose',
    emoji: '🧘',
    titleAr: 'وضعية الطفل (Balasana)',
    titleEn: "Child's Pose (Balasana)",
    durationMin: 5, durationSeconds: 300,
    color: '#4CAF82', bg: '#E8F5EF', accent: '#D6EFE3',
    descAr: 'تخفف الإرهاق النفسي والجسدي وترخي مفاصل الورك والفخذين والكاحلين',
    descEn: 'Relieves mental and physical fatigue, relaxes hips, thighs, and ankles',
    steps: [
      'اجلس على كعبيك مع ضم الركبتين أو تركهما متباعدتين قليلاً',
      'انحنِ من عند مفصل الورك للأمام ببطء وهدوء',
      'مدّ ذراعيك للأمام أو اتركهما بجانب الجسم',
      'ضع الجبهة على الأرض أو على وسادة للراحة',
      'استرخِ بعمق واسمح للجسم بالتخلص من التوتر',
      'ثبّت الوضعية حتى 5 دقائق مع تنفس عميق وهادئ',
    ],
    stepsEn: [
      'Sit on your heels with knees together or slightly apart',
      'Slowly hinge forward from your hips',
      'Extend your arms forward or rest them alongside your body',
      'Rest your forehead on the floor or on a pillow',
      'Relax deeply and let your body release tension',
      'Hold the pose for up to 5 minutes with deep, calm breathing',
    ],
    animType: 'sway', type: 'yoga',
  },
  {
    key: 'warriorTwo',
    emoji: '🥋',
    titleAr: 'وضعية المحارب الثاني (Warrior II)',
    titleEn: 'Warrior II (Virabhadrasana II)',
    durationMin: 3, durationSeconds: 180,
    color: '#4CAF82', bg: '#E8F5EF', accent: '#D6EFE3',
    descAr: 'تبني التحمل وتحسن التوازن مع تمديد وتقوية الجسم في نفس الوقت',
    descEn: 'Builds endurance and improves balance while stretching and strengthening the body',
    steps: [
      'قف في وضع مستقيم واخطُ بقدمك اليسرى للخلف بخطوة واسعة',
      'أدر القدم اليسرى قليلاً للخارج واجعل القدم اليمنى للأمام مباشرة',
      'افتح الوركين للجانب',
      'ارفع الذراعين لمستوى الكتفين أفقياً مع توجيه راحتي اليدين للأسفل',
      'اثنِ الركبة اليمنى بحيث تكون فوق الكاحل أو خلفه قليلاً',
      'حافظ على استقامة الساق الخلفية ووجّه نظرك للأمام فوق اليد الأمامية',
      'ثبّت الوضعية 20-60 ثانية ثم كرر على الجانب الآخر',
      'للدعم: استخدم كرسي تحت الفخذ الأمامي أو قف بجانب حائط',
    ],
    stepsEn: [
      'Stand tall and step your left foot back into a wide stance',
      'Turn your left foot slightly outward and point your right foot straight ahead',
      'Open your hips to the side',
      'Raise arms to shoulder height horizontally with palms facing down',
      'Bend your right knee so it is over or just behind the ankle',
      'Keep your back leg straight and gaze forward over your front hand',
      'Hold for 20-60 seconds then repeat on the other side',
      'Modification: use a chair under the front thigh or stand near a wall',
    ],
    animType: 'armRaise', type: 'yoga',
  },
  {
    key: 'jabPunches',
    emoji: '👊',
    titleAr: 'اللكمات الأمامية (Jab Punches)',
    titleEn: 'Jab Punches',
    durationMin: 5, durationSeconds: 300,
    color: '#4CAF82', bg: '#E8F5EF', accent: '#D6EFE3',
    descAr: 'تنشط الدورة الدموية وتقوي عضلات الذراعين والكتفين',
    descEn: 'Boosts circulation and strengthens arm and shoulder muscles',
    steps: [
      'قف مستقيماً وافتح قدميك بعرض الكتفين لتحسين التوازن',
      'كوّن قبضتين وضعهما أمام كتفيك مع توجيه راحتي اليدين للأمام',
      'اضرب بقبضتك اليسرى للأمام مع مد الذراع بالكامل',
      'عد إلى وضع البداية',
      'كرر الحركة بالذراع اليمنى — هذا تكرار واحد',
      'اعمل من 1 إلى 2 مجموعة، كل مجموعة 20 تكراراً',
    ],
    stepsEn: [
      'Stand straight with feet shoulder-width apart for better balance',
      'Form two fists and hold them in front of your shoulders, palms facing forward',
      'Punch your left fist straight forward with arm fully extended',
      'Return to the starting position',
      'Repeat with the right arm — this counts as one repetition',
      'Do 1 to 2 sets of 20 repetitions',
    ],
    animType: 'armRaise', type: 'yoga',
  },
  {
    key: 'comboPunches',
    emoji: '🥊',
    titleAr: 'اللكمات المركبة (Combination Punches)',
    titleEn: 'Combination Punches',
    durationMin: 5, durationSeconds: 300,
    color: '#4CAF82', bg: '#E8F5EF', accent: '#D6EFE3',
    descAr: 'تقوية عضلات الذراعين والكتفين مع تحسين التنسيق الحركي',
    descEn: 'Strengthens arms and shoulders while improving motor coordination',
    steps: [
      'قف مستقيماً وافتح قدميك بعرض الكتفين',
      'كوّن قبضتين وضعهما أمام كتفيك مع توجيه راحتي اليدين للداخل',
      'ارفع قبضة يدك اليسرى للأعلى مع فرد الذراع بالكامل',
      'ارجع إلى وضع البداية',
      'ارفع نفس القبضة اليسرى عبر جسمك أفقياً مع فرد الذراع بالكامل',
      'ارجع للبداية ثم كرر نفس الخطوات على الجانب الأيمن — هذا تكرار واحد',
      'اعمل من 1 إلى 2 مجموعة، كل مجموعة 20 تكراراً',
    ],
    stepsEn: [
      'Stand straight with feet shoulder-width apart',
      'Form two fists and hold them in front of your shoulders, palms facing inward',
      'Raise your left fist upward with arm fully extended',
      'Return to the starting position',
      'Raise the same left fist horizontally across your body with arm fully extended',
      'Return to start, then repeat on the right side — this counts as one repetition',
      'Do 1 to 2 sets of 20 repetitions',
    ],
    animType: 'armRaise', type: 'yoga',
  },

  // ─── Aerobic ──────────────────────────────────────────────
  {
    key: 'singleLegStand',
    emoji: '🦩',
    titleAr: 'الوقوف على قدم واحدة (Single Leg Stand)',
    titleEn: 'Single Leg Stand',
    durationMin: 5, durationSeconds: 300,
    color: '#E07B5C', bg: '#FDF0EB', accent: '#FAE2D6',
    descAr: 'يساعد على تحسين التوازن أثناء الوقوف والقدرة على المشي',
    descEn: 'Helps improve standing balance and walking ability',
    steps: [
      'للدعم، ضع يديك على الحائط أو على ظهر كرسي',
      'انقل وزنك إلى الساق الأقل استخداماً أو الأقل قوة',
      'ارفع القدم الأخرى ببطء عن الأرض',
      'حافظ على الوضع لمدة 20 ثانية، وحاول استخدام ذراعيك بأقل قدر ممكن للحفاظ على التوازن',
      'أنزل قدمك ببطء إلى الأرض',
      'كرر التمرين على الجانب الآخر',
      'يمكنك البدء بمدة أو عدد أقل من التكرارات، ثم زيادتها تدريجياً مع تحسن قدرتك',
    ],
    stepsEn: [
      'For support, place your hands on a wall or the back of a chair',
      'Shift your weight to your less-used or weaker leg',
      'Slowly lift the other foot off the ground',
      'Hold the position for 20 seconds, trying to use your arms as little as possible to maintain balance',
      'Slowly lower your foot back to the ground',
      'Repeat on the other side',
      'You can start with shorter durations or fewer repetitions, then gradually increase as your ability improves',
    ],
    animType: 'hipMarch', type: 'aerobic',
  },

  // ─── Endurance ────────────────────────────────────────────
  {
    key: 'armBottles',
    emoji: '💪',
    titleAr: 'تمارين الذراعين باستخدام زجاجات أثناء الجلوس',
    titleEn: 'Seated Arm Exercises with Bottles',
    durationMin: 5, durationSeconds: 300,
    color: '#D45BAA', bg: '#FCEEF8', accent: '#F8D6F0',
    descAr: 'تقوية عضلات الذراعين والكتفين باستخدام زجاجات مياه كأوزان خفيفة أثناء الجلوس',
    descEn: 'Strengthen arm and shoulder muscles using water bottles as light weights while seated',
    steps: [
      'اجلس على كرسي بظهر مستقيم وقدمان مسطحتان على الأرض',
      'أمسك زجاجة مياه في كل يد',
      'ارفع ذراعيك للأمام حتى مستوى الكتفين ببطء',
      'أنزل ذراعيك ببطء إلى وضع البداية',
      'ارفع ذراعيك للجانبين حتى مستوى الكتفين ببطء',
      'أنزل ذراعيك ببطء واكرر التمرين',
      'اعمل من 10 إلى 15 تكراراً لكل حركة',
    ],
    stepsEn: [
      'Sit on a chair with a straight back and feet flat on the floor',
      'Hold a water bottle in each hand',
      'Slowly raise both arms forward to shoulder level',
      'Slowly lower your arms back to the starting position',
      'Slowly raise both arms out to the sides to shoulder level',
      'Slowly lower your arms and repeat',
      'Do 10 to 15 repetitions for each movement',
    ],
    animType: 'armRaise', type: 'endurance',
  },
  {
    key: 'seatedEndurance',
    emoji: '🪑',
    titleAr: 'تمارين التحمل أثناء الجلوس',
    titleEn: 'Seated Endurance Exercises',
    durationMin: 5, durationSeconds: 300,
    color: '#D45BAA', bg: '#FCEEF8', accent: '#F8D6F0',
    descAr: 'تمارين تحمل شاملة تُؤدى أثناء الجلوس لتقوية الجسم بأمان',
    descEn: 'Comprehensive endurance exercises performed while seated to safely strengthen the body',
    steps: [
      'اجلس على حافة الكرسي مع استقامة الظهر',
      'ارفع ركبتك اليمنى ببطء نحو صدرك ثم أنزلها',
      'كرر مع الركبة اليسرى — هذا تكرار واحد',
      'مد ساقك اليمنى للأمام بشكل مستقيم ثم أنزلها',
      'كرر مع الساق اليسرى',
      'اعمل من 10 إلى 15 تكراراً لكل حركة مع تنفس منتظم',
    ],
    stepsEn: [
      'Sit on the edge of a chair with your back straight',
      'Slowly lift your right knee toward your chest then lower it',
      'Repeat with the left knee — this counts as one repetition',
      'Extend your right leg straight out in front then lower it',
      'Repeat with the left leg',
      'Do 10 to 15 repetitions for each movement with steady breathing',
    ],
    animType: 'hipMarch', type: 'endurance',
  },
  {
    key: 'neckFlexibility',
    emoji: '🧘',
    titleAr: 'مرونة الرقبة أثناء الاستلقاء',
    titleEn: 'Neck Flexibility While Lying Down',
    durationMin: 5, durationSeconds: 300,
    color: '#D45BAA', bg: '#FCEEF8', accent: '#F8D6F0',
    descAr: 'تحسين مرونة الرقبة وتخفيف التوتر في عضلاتها بشكل آمن أثناء الاستلقاء',
    descEn: 'Improve neck flexibility and relieve muscle tension safely while lying down',
    steps: [
      'استلقِ على ظهرك على سطح مستوٍ مريح',
      'أدر رأسك ببطء نحو الكتف الأيمن بقدر ما تستطيع دون ألم',
      'اثبت 5 ثوانٍ ثم عد للمنتصف ببطء',
      'أدر رأسك ببطء نحو الكتف الأيسر',
      'اثبت 5 ثوانٍ ثم عد للمنتصف ببطء',
      'أمِل رأسك ببطء للأمام نحو الصدر واثبت 5 ثوانٍ',
      'عد للمنتصف واكرر 5 إلى 10 مرات لكل اتجاه',
    ],
    stepsEn: [
      'Lie on your back on a comfortable flat surface',
      'Slowly turn your head toward your right shoulder as far as comfortable without pain',
      'Hold for 5 seconds then slowly return to center',
      'Slowly turn your head toward your left shoulder',
      'Hold for 5 seconds then slowly return to center',
      'Slowly tilt your head forward toward your chest and hold for 5 seconds',
      'Return to center and repeat 5 to 10 times in each direction',
    ],
    animType: 'sway', type: 'endurance',
  },
  {
    key: 'standUpStrength',
    emoji: '🏋️',
    titleAr: 'تمرين النهوض لتقوية الساقين',
    titleEn: 'Stand Up Exercise for Leg Strength',
    durationMin: 5, durationSeconds: 300,
    color: '#D45BAA', bg: '#FCEEF8', accent: '#F8D6F0',
    descAr: 'تقوية عضلات الساقين والركبتين وتحسين القدرة على النهوض والجلوس بأمان',
    descEn: 'Strengthen leg and knee muscles and improve the ability to stand and sit safely',
    steps: [
      'اجلس على كرسي ثابت بدون مسندين للذراعين إن أمكن',
      'ضع يديك على فخذيك أو امسك جانبي الكرسي للدعم',
      'أمِل جسمك للأمام قليلاً وانقل وزنك على قدميك',
      'ادفع من قدميك وانهض ببطء حتى تقف بشكل مستقيم',
      'اثبت واقفاً لثانية أو ثانيتين',
      'انحنِ ببطء للأمام وأنزل جسمك بتحكم حتى تجلس',
      'كرر من 8 إلى 10 مرات مع أخذ استراحة عند الحاجة',
    ],
    stepsEn: [
      'Sit on a stable chair without armrests if possible',
      'Place your hands on your thighs or hold the sides of the chair for support',
      'Lean your body slightly forward and shift your weight onto your feet',
      'Push through your feet and slowly rise until you are standing straight',
      'Hold the standing position for one or two seconds',
      'Slowly lean forward and lower your body in a controlled manner until seated',
      'Repeat 8 to 10 times, resting when needed',
    ],
    animType: 'bounce', type: 'endurance',
  },
  {
    key: 'upperBodyStretch',
    emoji: '🔄',
    titleAr: 'تمارين إطالة ودوران الجزء العلوي من الجسم',
    titleEn: 'Upper Body Stretching and Rotation Exercises',
    durationMin: 5, durationSeconds: 300,
    color: '#D45BAA', bg: '#FCEEF8', accent: '#F8D6F0',
    descAr: 'تحسين مرونة الجزء العلوي من الجسم وتخفيف تيبس الكتفين والظهر',
    descEn: 'Improve upper body flexibility and relieve stiffness in the shoulders and back',
    steps: [
      'اجلس أو قف باستقامة مع إبقاء الوركين ثابتين',
      'ضع يدك اليمنى على كتفك الأيسر',
      'أدر الجزء العلوي من جسمك ببطء نحو اليسار بقدر ما تستطيع بدون ألم',
      'اثبت 5 ثوانٍ ثم عد للمركز ببطء',
      'كرر على الجانب الأيمن',
      'مد ذراعيك للأعلى فوق رأسك ببطء واثبت 5 ثوانٍ',
      'أنزل ذراعيك ببطء واكرر كل حركة من 5 إلى 8 مرات',
    ],
    stepsEn: [
      'Sit or stand straight while keeping your hips still',
      'Place your right hand on your left shoulder',
      'Slowly rotate your upper body to the left as far as comfortable without pain',
      'Hold for 5 seconds then slowly return to center',
      'Repeat on the right side',
      'Slowly raise both arms above your head and hold for 5 seconds',
      'Slowly lower your arms and repeat each movement 5 to 8 times',
    ],
    animType: 'rollUp', type: 'endurance',
  },

  // ─── Strength ─────────────────────────────────────────────
  {
    key: 'marchingInPlace',
    emoji: '🚶',
    titleAr: 'السير في وضع الوقوف',
    titleEn: 'Marching in Place',
    durationMin: 5, durationSeconds: 300,
    color: '#7B5EA7', bg: '#F0EBF8', accent: '#E0D5F2',
    descAr: 'تحسين التوازن وتقوية عضلات الساقين والوركين مع تنشيط الدورة الدموية',
    descEn: 'Improves balance and strengthens leg and hip muscles while boosting circulation',
    steps: [
      'قف بجانب كرسي أو حائط للدعم عند الحاجة',
      'قف مستقيماً مع توزيع وزنك بالتساوي على قدميك',
      'ارفع ركبتك اليمنى ببطء نحو مستوى الورك',
      'أنزل القدم اليمنى ببطء إلى الأرض',
      'ارفع ركبتك اليسرى ببطء بنفس الطريقة',
      'استمر في رفع الركبتين بالتناوب كأنك تمشي في مكانك',
      'اعمل من 15 إلى 20 تكراراً لكل ساق مع تنفس منتظم',
    ],
    stepsEn: [
      'Stand next to a chair or wall for support if needed',
      'Stand straight with weight evenly distributed on both feet',
      'Slowly raise your right knee toward hip level',
      'Slowly lower your right foot back to the ground',
      'Slowly raise your left knee in the same way',
      'Continue alternating knees as if marching in place',
      'Do 15 to 20 repetitions for each leg with steady breathing',
    ],
    animType: 'hipMarch', type: 'strength',
  },
  {
    key: 'chairSquat',
    emoji: '🪑',
    titleAr: 'القرفصاء باستخدام الكرسي',
    titleEn: 'Chair Squat',
    durationMin: 5, durationSeconds: 300,
    color: '#7B5EA7', bg: '#F0EBF8', accent: '#E0D5F2',
    descAr: 'تقوية عضلات الفخذين والأرداف وتحسين القدرة على الجلوس والنهوض بأمان',
    descEn: 'Strengthens thigh and glute muscles and improves the ability to sit and stand safely',
    steps: [
      'ضع كرسياً ثابتاً خلفك وقف أمامه بمواجهة الأمام',
      'افتح قدميك بعرض الكتفين مع توجيه أصابع القدم للخارج قليلاً',
      'مد ذراعيك للأمام للتوازن أو امسك ظهر كرسي آخر للدعم',
      'انحنِ ببطء نحو الأسفل كأنك ستجلس حتى تلمس مؤخرتك الكرسي',
      'اثبت في الوضع لثانية أو ثانيتين',
      'ادفع من كعبيك وانهض ببطء إلى وضع الوقوف',
      'كرر من 8 إلى 12 مرة مع أخذ استراحة عند الحاجة',
    ],
    stepsEn: [
      'Place a stable chair behind you and stand in front of it facing forward',
      'Open your feet shoulder-width apart with toes pointing slightly outward',
      'Extend your arms forward for balance or hold another chair for support',
      'Slowly bend downward as if sitting until your bottom touches the chair',
      'Hold the position for one or two seconds',
      'Push through your heels and slowly rise to standing',
      'Repeat 8 to 12 times, resting when needed',
    ],
    animType: 'bounce', type: 'strength',
  },

  // ─── Coordination ─────────────────────────────────────────
  {
    key: 'towelArmStrength',
    emoji: '🧣',
    titleAr: 'تقوية الذراعين بالمنشفة أثناء الجلوس',
    titleEn: 'Seated Arm Strengthening with Towel',
    durationMin: 5, durationSeconds: 300,
    color: '#2A9D8F', bg: '#E6F5F3', accent: '#C8EBE7',
    descAr: 'تقوية عضلات الذراعين وتحسين التنسيق بين الطرفين العلويين باستخدام منشفة',
    descEn: 'Strengthens arm muscles and improves coordination between upper limbs using a towel',
    steps: [
      'اجلس على كرسي باستقامة مع إبقاء قدميك مسطحتين على الأرض',
      'أمسك منشفة صغيرة بكلتا يديك مع إبقاء ذراعيك ممدودتين للأمام',
      'اسحب المنشفة ببطء نحو صدرك مع ثني ذراعيك، كأنك تشد حبلاً',
      'اثبت في الوضع لثانيتين مع شد عضلات الظهر',
      'ارجع للوضع الممدود ببطء',
      'ارفع المنشفة أعلى رأسك ببطء مع مد الذراعين بالكامل واثبت 3 ثوانٍ',
      'أنزل ببطء واكرر من 10 إلى 15 تكراراً',
    ],
    stepsEn: [
      'Sit straight on a chair with feet flat on the floor',
      'Hold a small towel with both hands, arms extended forward',
      'Slowly pull the towel toward your chest while bending your arms, as if pulling a rope',
      'Hold the position for two seconds while engaging back muscles',
      'Slowly return to the extended position',
      'Slowly raise the towel above your head with arms fully extended and hold for 3 seconds',
      'Lower slowly and repeat 10 to 15 times',
    ],
    animType: 'armRaise', type: 'coordination',
  },
  {
    key: 'seatedBicycle',
    emoji: '🚴',
    titleAr: 'تمرين الدراجة الهوائية أثناء الجلوس',
    titleEn: 'Seated Bicycle Exercise',
    durationMin: 5, durationSeconds: 300,
    color: '#2A9D8F', bg: '#E6F5F3', accent: '#C8EBE7',
    descAr: 'تحسين التنسيق بين الطرفين العلوي والسفلي وتنشيط الدورة الدموية',
    descEn: 'Improves coordination between upper and lower limbs and boosts circulation',
    steps: [
      'اجلس على حافة كرسي باستقامة مع الإمساك بجانبيه للثبات',
      'ارفع ركبتك اليمنى ببطء نحو صدرك',
      'أنزل الساق اليمنى ببطء وارفع الركبة اليسرى في نفس الوقت',
      'استمر في حركة دوران كأنك تركب دراجة هوائية',
      'أضف حركة ذراعين: حرك يدك اليسرى للأمام مع رفع الركبة اليمنى',
      'ثم حرك يدك اليمنى للأمام مع رفع الركبة اليسرى',
      'اعمل من 15 إلى 20 دورة مع تنفس منتظم',
    ],
    stepsEn: [
      'Sit on the edge of a chair upright, holding its sides for stability',
      'Slowly raise your right knee toward your chest',
      'Slowly lower your right leg while raising your left knee at the same time',
      'Continue in a cycling motion as if riding a bicycle',
      'Add arm movement: move your left hand forward as you raise your right knee',
      'Then move your right hand forward as you raise your left knee',
      'Do 15 to 20 cycles with steady breathing',
    ],
    animType: 'hipMarch', type: 'coordination',
  },
  {
    key: 'seatedTwistKnee',
    emoji: '🔄',
    titleAr: 'لف الجسم ولمس الركبة المعاكسة أثناء الجلوس',
    titleEn: 'Seated Trunk Twist and Opposite Knee Touch',
    durationMin: 5, durationSeconds: 300,
    color: '#2A9D8F', bg: '#E6F5F3', accent: '#C8EBE7',
    descAr: 'تحسين التنسيق الحركي ومرونة الجذع وتقوية عضلات البطن والظهر',
    descEn: 'Improves motor coordination, trunk flexibility, and strengthens core and back muscles',
    steps: [
      'اجلس باستقامة على كرسي مع وضع قدميك مسطحتين على الأرض',
      'مد ذراعيك للجانبين بمستوى الكتفين',
      'الفع ذراعك اليمنى ببطء نحو ركبتك اليسرى مع تدوير الجذع',
      'اثبت لثانيتين مع الشعور بالشد في عضلات الجانب',
      'عد ببطء للوضع الأصلي مع فرد ذراعيك',
      'كرر مع الذراع اليسرى نحو الركبة اليمنى',
      'اعمل من 10 إلى 15 تكراراً لكل جانب مع تنفس منتظم',
    ],
    stepsEn: [
      'Sit straight on a chair with feet flat on the floor',
      'Extend both arms out to the sides at shoulder height',
      'Slowly bring your right arm toward your left knee while rotating your trunk',
      'Hold for two seconds feeling the stretch in your side muscles',
      'Slowly return to the starting position with arms extended',
      'Repeat with the left arm toward the right knee',
      'Do 10 to 15 repetitions on each side with steady breathing',
    ],
    animType: 'rollUp', type: 'coordination',
  },
  {
    key: 'lateralBalanceSeated',
    emoji: '⚖️',
    titleAr: 'تمرين التوازن الجانبي أثناء الجلوس',
    titleEn: 'Seated Lateral Balance Exercise',
    durationMin: 5, durationSeconds: 300,
    color: '#2A9D8F', bg: '#E6F5F3', accent: '#C8EBE7',
    descAr: 'تحسين التوازن الجانبي وتقوية عضلات الجانب والجذع أثناء الجلوس بأمان',
    descEn: 'Improves lateral balance and strengthens side and core muscles while seated safely',
    steps: [
      'اجلس على حافة الكرسي باستقامة دون الاستناد للظهر',
      'مد ذراعيك للجانبين حتى مستوى الكتفين للحفاظ على التوازن',
      'أمِل جسمك ببطء للجانب الأيمن مع إبقاء العمود الفقري مستقيماً',
      'اثبت في هذا الوضع لمدة 3 ثوانٍ',
      'عد ببطء للوضع المستقيم في المنتصف',
      'أمِل ببطء للجانب الأيسر بنفس الطريقة',
      'اعمل من 8 إلى 10 تكرارات لكل جانب',
    ],
    stepsEn: [
      'Sit on the edge of a chair upright without leaning on the back',
      'Extend both arms out to the sides at shoulder height for balance',
      'Slowly lean your body to the right while keeping your spine straight',
      'Hold this position for 3 seconds',
      'Slowly return upright to the center position',
      'Slowly lean to the left in the same way',
      'Do 8 to 10 repetitions on each side',
    ],
    animType: 'sway', type: 'coordination',
  },

  // ─── New Therapy Exercises ─────────────────────────────────
  {
    key: 'hipStrength',
    emoji: '🦵',
    titleAr: 'تمرين مشي الوركين (Hip Marching)',
    titleEn: 'Hip Marching',
    durationMin: 5, durationSeconds: 300,
    color: '#5B9BD5', bg: '#E8F1FB', accent: '#D0E5F7',
    descAr: 'تقوية مفاصل الورك وعضلاتها وتحسين حركة الساقين أثناء الجلوس',
    descEn: 'Strengthens hip joints and muscles and improves leg mobility while seated',
    steps: [
      'اجلس على كرسي بحيث يلامس ظهرك مسند الكرسي',
      'ضع يديك بشكل مريح على ساقيك',
      'ارفع ساقك اليسرى ببطء إلى الأعلى مباشرة، مع إبقاء الركبة مثنية',
      'اثبت على هذا الوضع مع العدّ حتى 5 أو طالما كان ذلك مريحاً لك',
      'أعد قدمك إلى الأرض ببطء',
      'كرر نفس الخطوات مع الساق الأخرى',
      'اعمل من 10 إلى 15 تكراراً لكل ساق مع تنفس منتظم',
    ],
    stepsEn: [
      'Sit on a chair so that your back touches the backrest',
      'Place your hands comfortably on your thighs',
      'Slowly lift your left leg straight up, keeping your knee bent',
      'Hold this position for a count of 5 or as long as comfortable',
      'Slowly lower your foot back to the floor',
      'Repeat the same steps with the other leg',
      'Do 10 to 15 repetitions for each leg with steady breathing',
    ],
    animType: 'hipMarch', type: 'therapy',
  },
  {
    key: 'legSwingBalance',
    emoji: '🦵',
    titleAr: 'تمرين ثني الساق للخلف',
    titleEn: 'Standing Leg Curl',
    durationMin: 5, durationSeconds: 300,
    color: '#5B9BD5', bg: '#E8F1FB', accent: '#D0E5F7',
    descAr: 'تقوية عضلات الفخذ الخلفية وتحسين التوازن أثناء الوقوف',
    descEn: 'Strengthens hamstring muscles and improves balance while standing',
    steps: [
      'قف وأمسك بمسند كرسي بكلتا يديك من أجل الدعم والتوازن',
      'ارفع كعب قدمك اليسرى للخلف باتجاه الأعلى، مع قصر الحركة على مفصل الركبة فقط',
      'ارفع ببطء حتى أقصى نقطة مريحة دون ألم',
      'اثبت في الوضع لمدة 3 ثوانٍ',
      'أنزل قدمك مرة أخرى إلى الأرض ببطء قدر الإمكان',
      'كرر مع القدم اليمنى',
      'اعمل من 10 إلى 15 تكراراً لكل ساق',
    ],
    stepsEn: [
      'Stand and hold the back of a chair with both hands for support and balance',
      'Raise your left heel backward and upward, keeping the movement limited to the knee joint only',
      'Lift slowly to the most comfortable point without pain',
      'Hold the position for 3 seconds',
      'Lower your foot back to the ground as slowly as possible',
      'Repeat with the right foot',
      'Do 10 to 15 repetitions for each leg',
    ],
    animType: 'hipMarch', type: 'therapy',
  },
  {
    key: 'pelvisTiltSeated',
    emoji: '🦶',
    titleAr: 'إرخاء وتر أكيليس (Achilles Tendon Release)',
    titleEn: 'Achilles Tendon Release',
    durationMin: 5, durationSeconds: 300,
    color: '#5B9BD5', bg: '#E8F1FB', accent: '#D0E5F7',
    descAr: 'إطالة وإرخاء وتر أكيليس والعضلات المشدودة في الجزء الخلفي من الساق والكعب',
    descEn: 'Stretches and relaxes the Achilles tendon and tight muscles in the back of the leg and heel',
    steps: [
      'اجلس على كرسي أو على الأرض وافرد إحدى ساقيك للأمام',
      'لف حزاماً أو شريطاً مطاطياً حول باطن القدم أسفل الأصابع مباشرة',
      'افرد ظهرك واجعل قوامك مستقيماً واشفط بطنك برفق للداخل',
      'حافظ على استقامة الجزء العلوي من جسمك',
      'اسحب الحزام أو الشريط ببطء نحوك لترجع قدمك باتجاهك',
      'يجب أن تقتصر الحركة على مفصل الكاحل فقط',
      'اثبت 5 ثوانٍ ثم أرخِ ببطء، واكرر من 10 إلى 15 مرة لكل قدم',
    ],
    stepsEn: [
      'Sit on a chair or on the floor and extend one leg straight in front',
      'Loop a strap or resistance band around the sole of your foot just below the toes',
      'Straighten your back, sit tall, and gently draw your belly inward',
      'Keep the upper part of your body straight and upright',
      'Slowly pull the strap or band toward you to bring your foot back toward you',
      'The movement should be limited to the ankle joint only',
      'Hold for 5 seconds then slowly release, repeat 10 to 15 times per foot',
    ],
    animType: 'achillesRelease', type: 'therapy',
  },
  {
    key: 'upperFlexArmStrength',
    emoji: '💺',
    titleAr: 'تمرين رفع الذراع على الكرسي (Arm Raise)',
    titleEn: 'Seated Arm Raise',
    durationMin: 5, durationSeconds: 300,
    color: '#5B9BD5', bg: '#E8F1FB', accent: '#D0E5F7',
    descAr: 'تحسين مرونة الكتف وتقوية عضلات الذراع العلوية مع تحسين التنفس',
    descEn: 'Improves shoulder flexibility and strengthens upper arm muscles while enhancing breathing',
    steps: [
      'اجلس على الكرسي مع إبقاء ظهرك مستقيماً ومفروداً تماماً على مسند الكرسي',
      'مد إحدى ذراعيك إلى جانبك',
      'ارفع هذه الذراع إلى الأعلى فوق رأسك بالكامل مع الحفاظ على استقامة ذراعك دون ثنيها',
      'بمجرد أن تصبح ذراعك فوق رأسك ثبتها في هذا الوضع',
      'خذ نَفَساً عميقاً وكاملاً (شهيق) ثم أخرجه بالكامل (زفير)',
      'أنزل ذراعك مرة أخرى إلى جانبك ببطء',
      'كرر مع الذراع الأخرى، اعمل من 8 إلى 10 تكرارات لكل ذراع',
    ],
    stepsEn: [
      'Sit on the chair keeping your back straight and fully supported against the backrest',
      'Extend one arm out to your side',
      'Raise that arm upward fully above your head while keeping it completely straight without bending',
      'Once your arm is above your head, hold it in this position',
      'Take a full deep breath in (inhale) then exhale completely',
      'Slowly lower your arm back to your side',
      'Repeat with the other arm, do 8 to 10 repetitions per arm',
    ],
    animType: 'armRaise', type: 'therapy',
  },

  // ─── New Yoga Exercise ────────────────────────────────────
  {
    key: 'lyingTwistArms',
    emoji: '🤸',
    titleAr: 'تمرين التدحرج لأعلى (Roll-ups) - بيلاتس',
    titleEn: 'Roll-ups (Pilates)',
    durationMin: 5, durationSeconds: 300,
    color: '#4CAF82', bg: '#E8F5EF', accent: '#D6EFE3',
    descAr: 'تقوية عضلات البطن والظهر وتحسين مرونة العمود الفقري من خلال حركة التدحرج اللطيفة',
    descEn: 'Strengthens core and back muscles and improves spinal flexibility through gentle rolling movement',
    steps: [
      'استلقِ على سجادة التمارين مع فرد ساقيك بشكل مستقيم',
      'مد يديك فوق رأسك وأمسك بطرف السجادة بأطراف أصابعك',
      'أخرج زفيراً وحاول شد بطنك للداخل باتجاه الأرض',
      'مع الاستمرار في الإمساك بالسجادة ارفع لوحي الكتف والجزء العلوي من الظهر ببطء',
      'ادفع رأسك برفق للخلف باتجاه السجادة أثناء الرفع',
      'توقف مؤقتاً لمدة ثانيتين محاولاً الشعور بانقباض عضلات البطن',
      'اعكس الحركة ببطء واخفض الجزء العلوي من ظهرك ليعود إلى الأرض',
    ],
    stepsEn: [
      'Lie on an exercise mat with your legs extended straight',
      'Extend your hands above your head and grasp the edge of the mat with your fingertips',
      'Exhale and try to draw your belly down toward the floor',
      'While continuing to hold the mat, slowly raise your shoulder blades and upper back',
      'Gently press your head back toward the mat as you lift',
      'Pause for two seconds trying to feel your abdominal muscles contract',
      'Slowly reverse the movement and lower your upper back to the floor',
    ],
    animType: 'rollUp', type: 'yoga',
  },

  // ─── New Aerobic Exercises ─────────────────────────────────
  {
    key: 'heelTapStanding',
    emoji: '👣',
    titleAr: 'تمرين النقر بكعب القدم أثناء الوقوف',
    titleEn: 'Standing Heel Tap',
    durationMin: 5, durationSeconds: 300,
    color: '#E07B5C', bg: '#FDF0EB', accent: '#FAE2D6',
    descAr: 'تحسين التوازن وتنشيط الدورة الدموية في القدمين والساقين أثناء الوقوف',
    descEn: 'Improves balance and boosts blood circulation in the feet and legs while standing',
    steps: [
      'قف بجانب حائط أو ظهر كرسي للدعم عند الحاجة',
      'قف مستقيماً مع توزيع وزنك بالتساوي على قدميك',
      'ارفع قدمك اليمنى للخلف قليلاً وانقر بكعبك بلطف على الأرض',
      'أعد القدم اليمنى لوضعها الأصلي',
      'كرر مع القدم اليسرى بالتناوب',
      'حافظ على التوازن والوضع المستقيم طوال التمرين',
      'اعمل من 15 إلى 20 تكراراً لكل قدم مع تنفس منتظم',
    ],
    stepsEn: [
      'Stand next to a wall or chair back for support if needed',
      'Stand straight with weight evenly distributed on both feet',
      'Lift your right foot slightly back and gently tap your heel on the floor',
      'Return your right foot to its starting position',
      'Repeat with the left foot alternating sides',
      'Maintain balance and upright posture throughout the exercise',
      'Do 15 to 20 repetitions for each foot with steady breathing',
    ],
    animType: 'hipMarch', type: 'aerobic',
  },
  {
    key: 'kneeCircleStanding',
    emoji: '🔵',
    titleAr: 'تمرين دوران الركبة أثناء الوقوف',
    titleEn: 'Standing Knee Circle',
    durationMin: 5, durationSeconds: 300,
    color: '#E07B5C', bg: '#FDF0EB', accent: '#FAE2D6',
    descAr: 'تحسين مرونة مفصل الركبة وتقوية العضلات المحيطة به',
    descEn: 'Improves knee joint flexibility and strengthens surrounding muscles',
    steps: [
      'قف مستقيماً وأمسك بظهر كرسي ثابت للدعم',
      'ارفع ركبتك اليمنى لأعلى برفق حتى مستوى الورك',
      'أدر ركبتك في دائرة صغيرة للخارج ثم للأسفل ثم للداخل',
      'أعد الركبة للأعلى وكرر الدوران',
      'اعمل 5 دورات في اتجاه عقارب الساعة ثم 5 دورات في الاتجاه المعاكس',
      'أنزل قدمك ببطء وغير إلى الساق اليسرى',
      'كرر نفس العدد من الدورات',
    ],
    stepsEn: [
      'Stand straight holding a sturdy chair back for support',
      'Gently raise your right knee up to hip level',
      'Circle your knee outward then downward then inward',
      'Bring the knee back up and repeat the circle',
      'Do 5 circles clockwise then 5 circles counterclockwise',
      'Slowly lower your foot and switch to the left leg',
      'Repeat the same number of circles',
    ],
    animType: 'hipMarch', type: 'aerobic',
  },
  {
    key: 'trunkRotationStanding',
    emoji: '🔄',
    titleAr: 'تمرين دوران الجذع أثناء الوقوف',
    titleEn: 'Standing Trunk Rotation',
    durationMin: 5, durationSeconds: 300,
    color: '#E07B5C', bg: '#FDF0EB', accent: '#FAE2D6',
    descAr: 'تحسين مرونة العمود الفقري وتقوية عضلات الجذع والظهر',
    descEn: 'Improves spinal flexibility and strengthens trunk and back muscles',
    steps: [
      'قف مستقيماً مع وضع يديك على الكتفين أو الوركين',
      'حافظ على ثبات الوركين وانظر للأمام',
      'أدر الجزء العلوي من جسمك ببطء نحو اليمين بقدر ما تستطيع',
      'اثبت في الوضع لمدة 3 ثوانٍ',
      'عد ببطء للمنتصف',
      'أدر الجذع ببطء نحو اليسار بنفس الطريقة',
      'اعمل من 10 إلى 12 تكراراً لكل اتجاه مع تنفس منتظم',
    ],
    stepsEn: [
      'Stand straight with hands placed on your shoulders or hips',
      'Keep your hips still and look straight ahead',
      'Slowly rotate your upper body to the right as far as comfortable',
      'Hold the position for 3 seconds',
      'Slowly return to center',
      'Slowly rotate your trunk to the left in the same way',
      'Do 10 to 12 repetitions in each direction with steady breathing',
    ],
    animType: 'rollUp', type: 'aerobic',
  },
  {
    key: 'toeTipHeelStand',
    emoji: '🧦',
    titleAr: 'تمرين الوقوف على أطراف الأصابع والكعبين',
    titleEn: 'Toe Tip and Heel Stand',
    durationMin: 5, durationSeconds: 300,
    color: '#E07B5C', bg: '#FDF0EB', accent: '#FAE2D6',
    descAr: 'تقوية عضلات أسفل الساقين والقدمين وتحسين التوازن والثبات',
    descEn: 'Strengthens lower leg and foot muscles and improves balance and stability',
    steps: [
      'قف مستقيماً وأمسك بظهر كرسي ثابت للدعم عند الحاجة',
      'ارفع ببطء على أطراف أصابع قدميك حتى أعلى نقطة ممكنة',
      'اثبت لمدة 2-3 ثوانٍ',
      'أنزل ببطء حتى تصبح قدمك مسطحة على الأرض',
      'ارفع أصابع قدميك للأعلى مع إبقاء الكعبين على الأرض',
      'اثبت لمدة 2-3 ثوانٍ',
      'أنزل ببطء واكرر من 10 إلى 15 مرة',
    ],
    stepsEn: [
      'Stand straight holding a sturdy chair back for support if needed',
      'Slowly rise up onto the tips of your toes as high as possible',
      'Hold for 2-3 seconds',
      'Slowly lower until your feet are flat on the floor',
      'Lift your toes upward while keeping your heels on the floor',
      'Hold for 2-3 seconds',
      'Lower slowly and repeat 10 to 15 times',
    ],
    animType: 'bounce', type: 'aerobic',
  },
  {
    key: 'trunkFlexibilityStanding',
    emoji: '🌊',
    titleAr: 'تمرين مرونة حركة الجذع أثناء الوقوف',
    titleEn: 'Standing Trunk Flexibility',
    durationMin: 5, durationSeconds: 300,
    color: '#E07B5C', bg: '#FDF0EB', accent: '#FAE2D6',
    descAr: 'تحسين مرونة الجذع والعمود الفقري وتخفيف تيبس الظهر',
    descEn: 'Improves trunk and spinal flexibility and relieves back stiffness',
    steps: [
      'قف مستقيماً مع وضع يديك على الوركين',
      'انحنِ ببطء للأمام من منطقة الخصر مع إبقاء الظهر مستقيماً',
      'اثبت لمدة 3 ثوانٍ',
      'عد ببطء للوضع المستقيم',
      'انحنِ برفق للخلف قدر المستطاع مع الحذر',
      'اثبت لمدة 3 ثوانٍ',
      'عد للوضع الأصلي وكرر من 5 إلى 8 مرات',
    ],
    stepsEn: [
      'Stand straight with hands on your hips',
      'Slowly bend forward from the waist while keeping your back straight',
      'Hold for 3 seconds',
      'Slowly return to the upright position',
      'Gently bend backward as far as comfortably possible',
      'Hold for 3 seconds',
      'Return to the starting position and repeat 5 to 8 times',
    ],
    animType: 'sway', type: 'aerobic',
  },

  // ─── New Strength Exercises ────────────────────────────────
  {
    key: 'armLegStrength',
    emoji: '💪',
    titleAr: 'تمرين تقوية الذراعين والساقين',
    titleEn: 'Arm and Leg Strengthening',
    durationMin: 5, durationSeconds: 300,
    color: '#7B5EA7', bg: '#F0EBF8', accent: '#E0D5F2',
    descAr: 'تقوية عضلات الذراعين والساقين معاً مع تحسين التنسيق والتوازن',
    descEn: 'Strengthens arm and leg muscles together while improving coordination and balance',
    steps: [
      'قف مستقيماً بجانب كرسي للدعم إذا لزم الأمر',
      'ارفع ذراعك اليمنى للأمام ببطء حتى مستوى الكتف',
      'في نفس الوقت ارفع ركبتك اليسرى ببطء حتى مستوى الورك',
      'اثبت في الوضع لمدة 3 ثوانٍ مع المحافظة على التوازن',
      'أنزل الذراع والساق ببطء معاً',
      'كرر مع الذراع اليسرى والركبة اليمنى',
      'اعمل من 8 إلى 12 تكراراً لكل جانب مع تنفس منتظم',
    ],
    stepsEn: [
      'Stand straight next to a chair for support if needed',
      'Slowly raise your right arm forward to shoulder level',
      'At the same time slowly raise your left knee to hip level',
      'Hold the position for 3 seconds while maintaining balance',
      'Slowly lower both the arm and leg together',
      'Repeat with the left arm and right knee',
      'Do 8 to 12 repetitions per side with steady breathing',
    ],
    animType: 'hipMarch', type: 'strength',
  },
  {
    key: 'standingArmTrunk',
    emoji: '🏋️',
    titleAr: 'تمرين السحب أثناء الوقوف (Standing Row)',
    titleEn: 'Standing Row',
    durationMin: 5, durationSeconds: 300,
    color: '#7B5EA7', bg: '#F0EBF8', accent: '#E0D5F2',
    descAr: 'تقوية عضلات الظهر والذراعين وجذع الجسم باستخدام شريط مقاومة أثناء الوقوف',
    descEn: 'Strengthens back, arm, and trunk muscles using a resistance band while standing',
    steps: [
      'ثبّت شريط التمرين المطاطي حول عمود أو قضيب ثابت',
      'أمسك بمقابض الشريط وابتعد عدة خطوات إلى الخلف',
      'حافظ على شدّ عضلات بطنك وجذعك مع ثني ركبتيك قليلاً',
      'اسحب المقابض نحوك حتى يصبح الكتفان بمحاذاة المرفقين',
      'اضغط لوحي الكتف باتجاه بعضهما',
      'مدّ ذراعيك ببطء للعودة إلى وضع البداية',
      'اعمل من 2 إلى 3 مجموعات، كل مجموعة 12 تكراراً',
    ],
    stepsEn: [
      'Secure a resistance band around a stable pole or bar',
      'Grasp the handles and step back several steps',
      'Keep your core and trunk muscles engaged with knees slightly bent',
      'Pull the handles toward you until your elbows are aligned with your shoulders',
      'Squeeze your shoulder blades together',
      'Slowly extend your arms back to the starting position',
      'Do 2 to 3 sets of 12 repetitions',
    ],
    animType: 'standingRow', type: 'strength',
  },
  {
    key: 'backBridgeLying',
    emoji: '🌉',
    titleAr: 'تمرين تقوس الظهر أثناء الاستلقاء (Back Bridge)',
    titleEn: 'Back Bridge (Lying)',
    durationMin: 5, durationSeconds: 300,
    color: '#7B5EA7', bg: '#F0EBF8', accent: '#E0D5F2',
    descAr: 'تقوية عضلات الظهر السفلي والأرداف وتحسين استقرار الحوض',
    descEn: 'Strengthens lower back and glute muscles and improves pelvic stability',
    steps: [
      'استلقِ على ظهرك على سطح مستوٍ ومريح',
      'ثنِ ركبتيك مع إبقاء قدميك مسطحتين على الأرض بعرض الوركين',
      'ضع ذراعيك بجانب جسمك مع توجيه راحتي اليدين للأسفل',
      'ارفع وركيك ببطء عن الأرض حتى يصبح جسمك في خط مستقيم من الكتفين حتى الركبتين',
      'اثبت في الوضع لمدة 3-5 ثوانٍ مع شد عضلات الأرداف',
      'أنزل وركيك ببطء إلى الأرض',
      'اعمل من 8 إلى 12 تكراراً مع تنفس منتظم',
    ],
    stepsEn: [
      'Lie on your back on a comfortable flat surface',
      'Bend your knees with feet flat on the floor hip-width apart',
      'Place your arms alongside your body with palms facing down',
      'Slowly lift your hips off the floor until your body forms a straight line from shoulders to knees',
      'Hold the position for 3-5 seconds while squeezing your glutes',
      'Slowly lower your hips back to the floor',
      'Do 8 to 12 repetitions with steady breathing',
    ],
    animType: 'bounce', type: 'strength',
  },

  // ─── New Endurance Exercise ────────────────────────────────
  {
    key: 'trunkBackFlexibility',
    emoji: '🌀',
    titleAr: 'تمارين مرونة الجذع والظهر',
    titleEn: 'Trunk and Back Flexibility Exercises',
    durationMin: 5, durationSeconds: 300,
    color: '#D45BAA', bg: '#FCEEF8', accent: '#F8D6F0',
    descAr: 'تحسين مرونة الجذع والظهر وتخفيف التيبس والألم في منطقة الظهر',
    descEn: 'Improves trunk and back flexibility and relieves stiffness and pain in the back area',
    steps: [
      'اجلس أو قف باستقامة مع إبقاء الوركين ثابتين',
      'انحنِ ببطء للأمام من منطقة الخصر مع إبقاء الظهر مستقيماً قدر الإمكان',
      'اثبت 5 ثوانٍ مع التنفس العميق',
      'عد ببطء للوضع الأصلي',
      'ادفع يديك للخلف خلف ظهرك وشبّك أصابعك',
      'ارفع يديك ببطء خلف ظهرك مع فتح الصدر',
      'أدر جسمك للجانبين 5 مرات لكل اتجاه ثم كرر الدورة من البداية',
    ],
    stepsEn: [
      'Sit or stand straight while keeping your hips still',
      'Slowly bend forward from the waist while keeping your back as straight as possible',
      'Hold for 5 seconds with deep breathing',
      'Slowly return to the starting position',
      'Clasp your hands behind your back',
      'Slowly raise your hands behind your back while opening your chest',
      'Rotate your trunk side to side 5 times each direction then repeat the cycle',
    ],
    animType: 'rollUp', type: 'endurance',
  },
];

export const ALL_DEFAULT_EXERCISES_MAP: Record<string, DefaultExercise> =
  Object.fromEntries(ALL_DEFAULT_EXERCISES.map(e => [e.key, e]));
