// utils/defaultExercises.ts
// Single source of truth for all built-in exercise data.
// Imported by exercises.tsx (patient view) and Docpatient.tsx (doctor assign).

export type ExSectionKey = 'therapy' | 'yoga' | 'aerobic' | 'endurance' | 'strength' | 'coordination';
export type AnimType = 'hipMarch' | 'armRaise' | 'standingRow' | 'legCurl' | 'rollUp' | 'achillesRelease' | 'bounce' | 'sway';

export type DefaultExercise = {
  key: string;
  emoji: string;
  titleAr: string;
  titleEn: string;
  durationMin: number;
  durationSeconds: number;
  color: string;
  bg: string;
  accent: string;
  descAr: string;
  descEn: string;
  steps: string[];
  stepsEn: string[];
  animType: AnimType;
  type: ExSectionKey;
};

export const ALL_DEFAULT_EXERCISES: DefaultExercise[] = [
  // ─── Therapy ──────────────────────────────────────────────
  {
    key: 'wristCurls',
    emoji: '🤲',
    titleAr: 'ثني الرسغ (Wrist Curls)',
    titleEn: 'Wrist Curls',
    durationMin: 5, durationSeconds: 300,
    color: '#5B9BD5', bg: '#E8F1FB', accent: '#D0E5F7',
    descAr: 'يزيد الثبات، ويقلل الرعشة، ويحسّن خفة حركة الأصابع واليدين',
    descEn: 'Increases stability, reduces tremors, and improves finger and hand dexterity',
    steps: [
      'استخدم دمبل بوزن من 1 إلى 5 أرطال (0.5 إلى 2.5 كجم)',
      'ضع يدك اليسرى ورسغك على حافة طاولة مع توجيه راحة اليد للأعلى',
      'امسك الوزن في يدك بإحكام',
      'ارفع الرسغ ببطء لأعلى قدر تستطيع',
      'حافظ على الوضعية لبضع ثوانٍ ثم أنزل ببطء',
      'اعمل من 1 إلى 2 مجموعة، كل مجموعة 12 تكراراً، ثم كرر على اليد اليمنى',
    ],
    stepsEn: [
      'Use a dumbbell weighing 1 to 5 pounds (0.5 to 2.5 kg)',
      'Place your left hand and wrist on the edge of a table with your palm facing up',
      'Hold the weight firmly in your hand',
      'Slowly raise your wrist upward as far as you can',
      'Hold the position for a few seconds then lower slowly',
      'Do 1 to 2 sets of 12 repetitions, then repeat with the right hand',
    ],
    animType: 'armRaise', type: 'therapy',
  },

  // ─── Yoga ─────────────────────────────────────────────────
  {
    key: 'childsPose',
    emoji: '🧘',
    titleAr: 'وضعية الطفل (Balasana)',
    titleEn: "Child's Pose (Balasana)",
    durationMin: 5, durationSeconds: 300,
    color: '#4CAF82', bg: '#E8F5EF', accent: '#D6EFE3',
    descAr: 'تخفف الإرهاق النفسي والجسدي وترخي مفاصل الورك والفخذين والكاحلين',
    descEn: 'Relieves mental and physical fatigue, relaxes hips, thighs, and ankles',
    steps: [
      'اجلس على كعبيك مع ضم الركبتين أو تركهما متباعدتين قليلاً',
      'انحنِ من عند مفصل الورك للأمام ببطء وهدوء',
      'مدّ ذراعيك للأمام أو اتركهما بجانب الجسم',
      'ضع الجبهة على الأرض أو على وسادة للراحة',
      'استرخِ بعمق واسمح للجسم بالتخلص من التوتر',
      'ثبّت الوضعية حتى 5 دقائق مع تنفس عميق وهادئ',
    ],
    stepsEn: [
      'Sit on your heels with knees together or slightly apart',
      'Slowly hinge forward from your hips',
      'Extend your arms forward or rest them alongside your body',
      'Rest your forehead on the floor or on a pillow',
      'Relax deeply and let your body release tension',
      'Hold the pose for up to 5 minutes with deep, calm breathing',
    ],
    animType: 'sway', type: 'yoga',
  },
  {
    key: 'warriorTwo',
    emoji: '🥋',
    titleAr: 'وضعية المحارب الثاني (Warrior II)',
    titleEn: 'Warrior II (Virabhadrasana II)',
    durationMin: 3, durationSeconds: 180,
    color: '#4CAF82', bg: '#E8F5EF', accent: '#D6EFE3',
    descAr: 'تبني التحمل وتحسن التوازن مع تمديد وتقوية الجسم في نفس الوقت',
    descEn: 'Builds endurance and improves balance while stretching and strengthening the body',
    steps: [
      'قف في وضع مستقيم واخطُ بقدمك اليسرى للخلف بخطوة واسعة',
      'أدر القدم اليسرى قليلاً للخارج واجعل القدم اليمنى للأمام مباشرة',
      'افتح الوركين للجانب',
      'ارفع الذراعين لمستوى الكتفين أفقياً مع توجيه راحتي اليدين للأسفل',
      'اثنِ الركبة اليمنى بحيث تكون فوق الكاحل أو خلفه قليلاً',
      'حافظ على استقامة الساق الخلفية ووجّه نظرك للأمام فوق اليد الأمامية',
      'ثبّت الوضعية 20-60 ثانية ثم كرر على الجانب الآخر',
      'للدعم: استخدم كرسي تحت الفخذ الأمامي أو قف بجانب حائط',
    ],
    stepsEn: [
      'Stand tall and step your left foot back into a wide stance',
      'Turn your left foot slightly outward and point your right foot straight ahead',
      'Open your hips to the side',
      'Raise arms to shoulder height horizontally with palms facing down',
      'Bend your right knee so it is over or just behind the ankle',
      'Keep your back leg straight and gaze forward over your front hand',
      'Hold for 20-60 seconds then repeat on the other side',
      'Modification: use a chair under the front thigh or stand near a wall',
    ],
    animType: 'armRaise', type: 'yoga',
  },
  {
    key: 'jabPunches',
    emoji: '👊',
    titleAr: 'اللكمات الأمامية (Jab Punches)',
    titleEn: 'Jab Punches',
    durationMin: 5, durationSeconds: 300,
    color: '#4CAF82', bg: '#E8F5EF', accent: '#D6EFE3',
    descAr: 'تنشط الدورة الدموية وتقوي عضلات الذراعين والكتفين',
    descEn: 'Boosts circulation and strengthens arm and shoulder muscles',
    steps: [
      'قف مستقيماً وافتح قدميك بعرض الكتفين لتحسين التوازن',
      'كوّن قبضتين وضعهما أمام كتفيك مع توجيه راحتي اليدين للأمام',
      'اضرب بقبضتك اليسرى للأمام مع مد الذراع بالكامل',
      'عد إلى وضع البداية',
      'كرر الحركة بالذراع اليمنى — هذا تكرار واحد',
      'اعمل من 1 إلى 2 مجموعة، كل مجموعة 20 تكراراً',
    ],
    stepsEn: [
      'Stand straight with feet shoulder-width apart for better balance',
      'Form two fists and hold them in front of your shoulders, palms facing forward',
      'Punch your left fist straight forward with arm fully extended',
      'Return to the starting position',
      'Repeat with the right arm — this counts as one repetition',
      'Do 1 to 2 sets of 20 repetitions',
    ],
    animType: 'armRaise', type: 'yoga',
  },
  {
    key: 'comboPunches',
    emoji: '🥊',
    titleAr: 'اللكمات المركبة (Combination Punches)',
    titleEn: 'Combination Punches',
    durationMin: 5, durationSeconds: 300,
    color: '#4CAF82', bg: '#E8F5EF', accent: '#D6EFE3',
    descAr: 'تقوية عضلات الذراعين والكتفين مع تحسين التنسيق الحركي',
    descEn: 'Strengthens arms and shoulders while improving motor coordination',
    steps: [
      'قف مستقيماً وافتح قدميك بعرض الكتفين',
      'كوّن قبضتين وضعهما أمام كتفيك مع توجيه راحتي اليدين للداخل',
      'ارفع قبضة يدك اليسرى للأعلى مع فرد الذراع بالكامل',
      'ارجع إلى وضع البداية',
      'ارفع نفس القبضة اليسرى عبر جسمك أفقياً مع فرد الذراع بالكامل',
      'ارجع للبداية ثم كرر نفس الخطوات على الجانب الأيمن — هذا تكرار واحد',
      'اعمل من 1 إلى 2 مجموعة، كل مجموعة 20 تكراراً',
    ],
    stepsEn: [
      'Stand straight with feet shoulder-width apart',
      'Form two fists and hold them in front of your shoulders, palms facing inward',
      'Raise your left fist upward with arm fully extended',
      'Return to the starting position',
      'Raise the same left fist horizontally across your body with arm fully extended',
      'Return to start, then repeat on the right side — this counts as one repetition',
      'Do 1 to 2 sets of 20 repetitions',
    ],
    animType: 'armRaise', type: 'yoga',
  },

  // ─── Aerobic ──────────────────────────────────────────────
  {
    key: 'singleLegStand',
    emoji: '🦩',
    titleAr: 'الوقوف على قدم واحدة (Single Leg Stand)',
    titleEn: 'Single Leg Stand',
    durationMin: 5, durationSeconds: 300,
    color: '#E07B5C', bg: '#FDF0EB', accent: '#FAE2D6',
    descAr: 'يساعد على تحسين التوازن أثناء الوقوف والقدرة على المشي',
    descEn: 'Helps improve standing balance and walking ability',
    steps: [
      'للدعم، ضع يديك على الحائط أو على ظهر كرسي',
      'انقل وزنك إلى الساق الأقل استخداماً أو الأقل قوة',
      'ارفع القدم الأخرى ببطء عن الأرض',
      'حافظ على الوضع لمدة 20 ثانية، وحاول استخدام ذراعيك بأقل قدر ممكن للحفاظ على التوازن',
      'أنزل قدمك ببطء إلى الأرض',
      'كرر التمرين على الجانب الآخر',
      'يمكنك البدء بمدة أو عدد أقل من التكرارات، ثم زيادتها تدريجياً مع تحسن قدرتك',
    ],
    stepsEn: [
      'For support, place your hands on a wall or the back of a chair',
      'Shift your weight to your less-used or weaker leg',
      'Slowly lift the other foot off the ground',
      'Hold the position for 20 seconds, trying to use your arms as little as possible to maintain balance',
      'Slowly lower your foot back to the ground',
      'Repeat on the other side',
      'You can start with shorter durations or fewer repetitions, then gradually increase as your ability improves',
    ],
    animType: 'hipMarch', type: 'aerobic',
  },

  // ─── Endurance ────────────────────────────────────────────
  {
    key: 'armBottles',
    emoji: '💪',
    titleAr: 'تمارين الذراعين باستخدام زجاجات أثناء الجلوس',
    titleEn: 'Seated Arm Exercises with Bottles',
    durationMin: 5, durationSeconds: 300,
    color: '#D45BAA', bg: '#FCEEF8', accent: '#F8D6F0',
    descAr: 'تقوية عضلات الذراعين والكتفين باستخدام زجاجات مياه كأوزان خفيفة أثناء الجلوس',
    descEn: 'Strengthen arm and shoulder muscles using water bottles as light weights while seated',
    steps: [
      'اجلس على كرسي بظهر مستقيم وقدمان مسطحتان على الأرض',
      'أمسك زجاجة مياه في كل يد',
      'ارفع ذراعيك للأمام حتى مستوى الكتفين ببطء',
      'أنزل ذراعيك ببطء إلى وضع البداية',
      'ارفع ذراعيك للجانبين حتى مستوى الكتفين ببطء',
      'أنزل ذراعيك ببطء واكرر التمرين',
      'اعمل من 10 إلى 15 تكراراً لكل حركة',
    ],
    stepsEn: [
      'Sit on a chair with a straight back and feet flat on the floor',
      'Hold a water bottle in each hand',
      'Slowly raise both arms forward to shoulder level',
      'Slowly lower your arms back to the starting position',
      'Slowly raise both arms out to the sides to shoulder level',
      'Slowly lower your arms and repeat',
      'Do 10 to 15 repetitions for each movement',
    ],
    animType: 'armRaise', type: 'endurance',
  },
  {
    key: 'seatedEndurance',
    emoji: '🪑',
    titleAr: 'تمارين التحمل أثناء الجلوس',
    titleEn: 'Seated Endurance Exercises',
    durationMin: 5, durationSeconds: 300,
    color: '#D45BAA', bg: '#FCEEF8', accent: '#F8D6F0',
    descAr: 'تمارين تحمل شاملة تُؤدى أثناء الجلوس لتقوية الجسم بأمان',
    descEn: 'Comprehensive endurance exercises performed while seated to safely strengthen the body',
    steps: [
      'اجلس على حافة الكرسي مع استقامة الظهر',
      'ارفع ركبتك اليمنى ببطء نحو صدرك ثم أنزلها',
      'كرر مع الركبة اليسرى — هذا تكرار واحد',
      'مد ساقك اليمنى للأمام بشكل مستقيم ثم أنزلها',
      'كرر مع الساق اليسرى',
      'اعمل من 10 إلى 15 تكراراً لكل حركة مع تنفس منتظم',
    ],
    stepsEn: [
      'Sit on the edge of a chair with your back straight',
      'Slowly lift your right knee toward your chest then lower it',
      'Repeat with the left knee — this counts as one repetition',
      'Extend your right leg straight out in front then lower it',
      'Repeat with the left leg',
      'Do 10 to 15 repetitions for each movement with steady breathing',
    ],
    animType: 'hipMarch', type: 'endurance',
  },
  {
    key: 'neckFlexibility',
    emoji: '🧘',
    titleAr: 'مرونة الرقبة أثناء الاستلقاء',
    titleEn: 'Neck Flexibility While Lying Down',
    durationMin: 5, durationSeconds: 300,
    color: '#D45BAA', bg: '#FCEEF8', accent: '#F8D6F0',
    descAr: 'تحسين مرونة الرقبة وتخفيف التوتر في عضلاتها بشكل آمن أثناء الاستلقاء',
    descEn: 'Improve neck flexibility and relieve muscle tension safely while lying down',
    steps: [
      'استلقِ على ظهرك على سطح مستوٍ مريح',
      'أدر رأسك ببطء نحو الكتف الأيمن بقدر ما تستطيع دون ألم',
      'اثبت 5 ثوانٍ ثم عد للمنتصف ببطء',
      'أدر رأسك ببطء نحو الكتف الأيسر',
      'اثبت 5 ثوانٍ ثم عد للمنتصف ببطء',
      'أمِل رأسك ببطء للأمام نحو الصدر واثبت 5 ثوانٍ',
      'عد للمنتصف واكرر 5 إلى 10 مرات لكل اتجاه',
    ],
    stepsEn: [
      'Lie on your back on a comfortable flat surface',
      'Slowly turn your head toward your right shoulder as far as comfortable without pain',
      'Hold for 5 seconds then slowly return to center',
      'Slowly turn your head toward your left shoulder',
      'Hold for 5 seconds then slowly return to center',
      'Slowly tilt your head forward toward your chest and hold for 5 seconds',
      'Return to center and repeat 5 to 10 times in each direction',
    ],
    animType: 'sway', type: 'endurance',
  },
  {
    key: 'standUpStrength',
    emoji: '🏋️',
    titleAr: 'تمرين النهوض لتقوية الساقين',
    titleEn: 'Stand Up Exercise for Leg Strength',
    durationMin: 5, durationSeconds: 300,
    color: '#D45BAA', bg: '#FCEEF8', accent: '#F8D6F0',
    descAr: 'تقوية عضلات الساقين والركبتين وتحسين القدرة على النهوض والجلوس بأمان',
    descEn: 'Strengthen leg and knee muscles and improve the ability to stand and sit safely',
    steps: [
      'اجلس على كرسي ثابت بدون مسندين للذراعين إن أمكن',
      'ضع يديك على فخذيك أو امسك جانبي الكرسي للدعم',
      'أمِل جسمك للأمام قليلاً وانقل وزنك على قدميك',
      'ادفع من قدميك وانهض ببطء حتى تقف بشكل مستقيم',
      'اثبت واقفاً لثانية أو ثانيتين',
      'انحنِ ببطء للأمام وأنزل جسمك بتحكم حتى تجلس',
      'كرر من 8 إلى 10 مرات مع أخذ استراحة عند الحاجة',
    ],
    stepsEn: [
      'Sit on a stable chair without armrests if possible',
      'Place your hands on your thighs or hold the sides of the chair for support',
      'Lean your body slightly forward and shift your weight onto your feet',
      'Push through your feet and slowly rise until you are standing straight',
      'Hold the standing position for one or two seconds',
      'Slowly lean forward and lower your body in a controlled manner until seated',
      'Repeat 8 to 10 times, resting when needed',
    ],
    animType: 'bounce', type: 'endurance',
  },
  {
    key: 'upperBodyStretch',
    emoji: '🔄',
    titleAr: 'تمارين إطالة ودوران الجزء العلوي من الجسم',
    titleEn: 'Upper Body Stretching and Rotation Exercises',
    durationMin: 5, durationSeconds: 300,
    color: '#D45BAA', bg: '#FCEEF8', accent: '#F8D6F0',
    descAr: 'تحسين مرونة الجزء العلوي من الجسم وتخفيف تيبس الكتفين والظهر',
    descEn: 'Improve upper body flexibility and relieve stiffness in the shoulders and back',
    steps: [
      'اجلس أو قف باستقامة مع إبقاء الوركين ثابتين',
      'ضع يدك اليمنى على كتفك الأيسر',
      'أدر الجزء العلوي من جسمك ببطء نحو اليسار بقدر ما تستطيع بدون ألم',
      'اثبت 5 ثوانٍ ثم عد للمركز ببطء',
      'كرر على الجانب الأيمن',
      'مد ذراعيك للأعلى فوق رأسك ببطء واثبت 5 ثوانٍ',
      'أنزل ذراعيك ببطء واكرر كل حركة من 5 إلى 8 مرات',
    ],
    stepsEn: [
      'Sit or stand straight while keeping your hips still',
      'Place your right hand on your left shoulder',
      'Slowly rotate your upper body to the left as far as comfortable without pain',
      'Hold for 5 seconds then slowly return to center',
      'Repeat on the right side',
      'Slowly raise both arms above your head and hold for 5 seconds',
      'Slowly lower your arms and repeat each movement 5 to 8 times',
    ],
    animType: 'rollUp', type: 'endurance',
  },

  // ─── Strength ─────────────────────────────────────────────
  {
    key: 'marchingInPlace',
    emoji: '🚶',
    titleAr: 'السير في وضع الوقوف',
    titleEn: 'Marching in Place',
    durationMin: 5, durationSeconds: 300,
    color: '#7B5EA7', bg: '#F0EBF8', accent: '#E0D5F2',
    descAr: 'تحسين التوازن وتقوية عضلات الساقين والوركين مع تنشيط الدورة الدموية',
    descEn: 'Improves balance and strengthens leg and hip muscles while boosting circulation',
    steps: [
      'قف بجانب كرسي أو حائط للدعم عند الحاجة',
      'قف مستقيماً مع توزيع وزنك بالتساوي على قدميك',
      'ارفع ركبتك اليمنى ببطء نحو مستوى الورك',
      'أنزل القدم اليمنى ببطء إلى الأرض',
      'ارفع ركبتك اليسرى ببطء بنفس الطريقة',
      'استمر في رفع الركبتين بالتناوب كأنك تمشي في مكانك',
      'اعمل من 15 إلى 20 تكراراً لكل ساق مع تنفس منتظم',
    ],
    stepsEn: [
      'Stand next to a chair or wall for support if needed',
      'Stand straight with weight evenly distributed on both feet',
      'Slowly raise your right knee toward hip level',
      'Slowly lower your right foot back to the ground',
      'Slowly raise your left knee in the same way',
      'Continue alternating knees as if marching in place',
      'Do 15 to 20 repetitions for each leg with steady breathing',
    ],
    animType: 'hipMarch', type: 'strength',
  },
  {
    key: 'chairSquat',
    emoji: '🪑',
    titleAr: 'القرفصاء باستخدام الكرسي',
    titleEn: 'Chair Squat',
    durationMin: 5, durationSeconds: 300,
    color: '#7B5EA7', bg: '#F0EBF8', accent: '#E0D5F2',
    descAr: 'تقوية عضلات الفخذين والأرداف وتحسين القدرة على الجلوس والنهوض بأمان',
    descEn: 'Strengthens thigh and glute muscles and improves the ability to sit and stand safely',
    steps: [
      'ضع كرسياً ثابتاً خلفك وقف أمامه بمواجهة الأمام',
      'افتح قدميك بعرض الكتفين مع توجيه أصابع القدم للخارج قليلاً',
      'مد ذراعيك للأمام للتوازن أو امسك ظهر كرسي آخر للدعم',
      'انحنِ ببطء نحو الأسفل كأنك ستجلس حتى تلمس مؤخرتك الكرسي',
      'اثبت في الوضع لثانية أو ثانيتين',
      'ادفع من كعبيك وانهض ببطء إلى وضع الوقوف',
      'كرر من 8 إلى 12 مرة مع أخذ استراحة عند الحاجة',
    ],
    stepsEn: [
      'Place a stable chair behind you and stand in front of it facing forward',
      'Open your feet shoulder-width apart with toes pointing slightly outward',
      'Extend your arms forward for balance or hold another chair for support',
      'Slowly bend downward as if sitting until your bottom touches the chair',
      'Hold the position for one or two seconds',
      'Push through your heels and slowly rise to standing',
      'Repeat 8 to 12 times, resting when needed',
    ],
    animType: 'bounce', type: 'strength',
  },

  // ─── Coordination ─────────────────────────────────────────
  {
    key: 'towelArmStrength',
    emoji: '🧣',
    titleAr: 'تقوية الذراعين بالمنشفة أثناء الجلوس',
    titleEn: 'Seated Arm Strengthening with Towel',
    durationMin: 5, durationSeconds: 300,
    color: '#2A9D8F', bg: '#E6F5F3', accent: '#C8EBE7',
    descAr: 'تقوية عضلات الذراعين وتحسين التنسيق بين الطرفين العلويين باستخدام منشفة',
    descEn: 'Strengthens arm muscles and improves coordination between upper limbs using a towel',
    steps: [
      'اجلس على كرسي باستقامة مع إبقاء قدميك مسطحتين على الأرض',
      'أمسك منشفة صغيرة بكلتا يديك مع إبقاء ذراعيك ممدودتين للأمام',
      'اسحب المنشفة ببطء نحو صدرك مع ثني ذراعيك، كأنك تشد حبلاً',
      'اثبت في الوضع لثانيتين مع شد عضلات الظهر',
      'ارجع للوضع الممدود ببطء',
      'ارفع المنشفة أعلى رأسك ببطء مع مد الذراعين بالكامل واثبت 3 ثوانٍ',
      'أنزل ببطء واكرر من 10 إلى 15 تكراراً',
    ],
    stepsEn: [
      'Sit straight on a chair with feet flat on the floor',
      'Hold a small towel with both hands, arms extended forward',
      'Slowly pull the towel toward your chest while bending your arms, as if pulling a rope',
      'Hold the position for two seconds while engaging back muscles',
      'Slowly return to the extended position',
      'Slowly raise the towel above your head with arms fully extended and hold for 3 seconds',
      'Lower slowly and repeat 10 to 15 times',
    ],
    animType: 'armRaise', type: 'coordination',
  },
  {
    key: 'seatedBicycle',
    emoji: '🚴',
    titleAr: 'تمرين الدراجة الهوائية أثناء الجلوس',
    titleEn: 'Seated Bicycle Exercise',
    durationMin: 5, durationSeconds: 300,
    color: '#2A9D8F', bg: '#E6F5F3', accent: '#C8EBE7',
    descAr: 'تحسين التنسيق بين الطرفين العلوي والسفلي وتنشيط الدورة الدموية',
    descEn: 'Improves coordination between upper and lower limbs and boosts circulation',
    steps: [
      'اجلس على حافة كرسي باستقامة مع الإمساك بجانبيه للثبات',
      'ارفع ركبتك اليمنى ببطء نحو صدرك',
      'أنزل الساق اليمنى ببطء وارفع الركبة اليسرى في نفس الوقت',
      'استمر في حركة دوران كأنك تركب دراجة هوائية',
      'أضف حركة ذراعين: حرك يدك اليسرى للأمام مع رفع الركبة اليمنى',
      'ثم حرك يدك اليمنى للأمام مع رفع الركبة اليسرى',
      'اعمل من 15 إلى 20 دورة مع تنفس منتظم',
    ],
    stepsEn: [
      'Sit on the edge of a chair upright, holding its sides for stability',
      'Slowly raise your right knee toward your chest',
      'Slowly lower your right leg while raising your left knee at the same time',
      'Continue in a cycling motion as if riding a bicycle',
      'Add arm movement: move your left hand forward as you raise your right knee',
      'Then move your right hand forward as you raise your left knee',
      'Do 15 to 20 cycles with steady breathing',
    ],
    animType: 'hipMarch', type: 'coordination',
  },
];

export const ALL_DEFAULT_EXERCISES_MAP: Record<string, DefaultExercise> =
  Object.fromEntries(ALL_DEFAULT_EXERCISES.map(e => [e.key, e]));
