/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/energy`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/langchoose`; params?: Router.UnknownInputParams; } | { pathname: `/startup`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `/auth/sign-up-1`; params?: Router.UnknownInputParams; } | { pathname: `/auth/sign-up-2`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/exercises`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/home`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/more`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/notification`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/notificationService`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/tasks`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/energy`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/langchoose`; params?: Router.UnknownOutputParams; } | { pathname: `/startup`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/sign-in`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/sign-up-1`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/sign-up-2`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/exercises`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/home`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/more`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/notification`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/notificationService`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/tasks`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/energy${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/langchoose${`?${string}` | `#${string}` | ''}` | `/startup${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/auth/sign-in${`?${string}` | `#${string}` | ''}` | `/auth/sign-up-1${`?${string}` | `#${string}` | ''}` | `/auth/sign-up-2${`?${string}` | `#${string}` | ''}` | `/tabs/exercises${`?${string}` | `#${string}` | ''}` | `/tabs/home${`?${string}` | `#${string}` | ''}` | `/tabs/more${`?${string}` | `#${string}` | ''}` | `/tabs/notification${`?${string}` | `#${string}` | ''}` | `/tabs/notificationService${`?${string}` | `#${string}` | ''}` | `/tabs/tasks${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/energy`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/langchoose`; params?: Router.UnknownInputParams; } | { pathname: `/startup`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `/auth/sign-up-1`; params?: Router.UnknownInputParams; } | { pathname: `/auth/sign-up-2`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/exercises`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/home`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/more`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/notification`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/notificationService`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/tasks`; params?: Router.UnknownInputParams; };
    }
  }
}
